// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/client/account"
	"github.com/becoded/billit/client/accountant"
	"github.com/becoded/billit/client/cashbook"
	"github.com/becoded/billit/client/daily_receipt"
	"github.com/becoded/billit/client/document"
	"github.com/becoded/billit/client/einvoice"
	"github.com/becoded/billit/client/file"
	"github.com/becoded/billit/client/financial_transaction"
	"github.com/becoded/billit/client/g_l_account"
	"github.com/becoded/billit/client/journal"
	"github.com/becoded/billit/client/misc"
	"github.com/becoded/billit/client/o_auth2"
	"github.com/becoded/billit/client/order"
	"github.com/becoded/billit/client/party"
	"github.com/becoded/billit/client/peppol"
	"github.com/becoded/billit/client/product"
	"github.com/becoded/billit/client/report"
	"github.com/becoded/billit/client/to_process"
	"github.com/becoded/billit/client/webhook"
)

// Default billit API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.billit.be"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new billit API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *BillitAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new billit API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *BillitAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new billit API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *BillitAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(BillitAPI)
	cli.Transport = transport
	cli.Account = account.New(transport, formats)
	cli.Accountant = accountant.New(transport, formats)
	cli.Cashbook = cashbook.New(transport, formats)
	cli.DailyReceipt = daily_receipt.New(transport, formats)
	cli.Document = document.New(transport, formats)
	cli.Einvoice = einvoice.New(transport, formats)
	cli.File = file.New(transport, formats)
	cli.FinancialTransaction = financial_transaction.New(transport, formats)
	cli.GlAccount = g_l_account.New(transport, formats)
	cli.Journal = journal.New(transport, formats)
	cli.Misc = misc.New(transport, formats)
	cli.OAuth2 = o_auth2.New(transport, formats)
	cli.Order = order.New(transport, formats)
	cli.Party = party.New(transport, formats)
	cli.Peppol = peppol.New(transport, formats)
	cli.Product = product.New(transport, formats)
	cli.Report = report.New(transport, formats)
	cli.ToProcess = to_process.New(transport, formats)
	cli.Webhook = webhook.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// BillitAPI is a client for billit API
type BillitAPI struct {
	Account account.ClientService

	Accountant accountant.ClientService

	Cashbook cashbook.ClientService

	DailyReceipt daily_receipt.ClientService

	Document document.ClientService

	Einvoice einvoice.ClientService

	File file.ClientService

	FinancialTransaction financial_transaction.ClientService

	GlAccount g_l_account.ClientService

	Journal journal.ClientService

	Misc misc.ClientService

	OAuth2 o_auth2.ClientService

	Order order.ClientService

	Party party.ClientService

	Peppol peppol.ClientService

	Product product.ClientService

	Report report.ClientService

	ToProcess to_process.ClientService

	Webhook webhook.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *BillitAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Account.SetTransport(transport)
	c.Accountant.SetTransport(transport)
	c.Cashbook.SetTransport(transport)
	c.DailyReceipt.SetTransport(transport)
	c.Document.SetTransport(transport)
	c.Einvoice.SetTransport(transport)
	c.File.SetTransport(transport)
	c.FinancialTransaction.SetTransport(transport)
	c.GlAccount.SetTransport(transport)
	c.Journal.SetTransport(transport)
	c.Misc.SetTransport(transport)
	c.OAuth2.SetTransport(transport)
	c.Order.SetTransport(transport)
	c.Party.SetTransport(transport)
	c.Peppol.SetTransport(transport)
	c.Product.SetTransport(transport)
	c.Report.SetTransport(transport)
	c.ToProcess.SetTransport(transport)
	c.Webhook.SetTransport(transport)
}
