// Code generated by go-swagger; DO NOT EDIT.

package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// MiscGetCompanySearchReader is a Reader for the MiscGetCompanySearch structure.
type MiscGetCompanySearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MiscGetCompanySearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMiscGetCompanySearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/misc/companysearch/{Keywords}] Misc_GetCompanySearch", response, response.Code())
	}
}

// NewMiscGetCompanySearchOK creates a MiscGetCompanySearchOK with default headers values
func NewMiscGetCompanySearchOK() *MiscGetCompanySearchOK {
	return &MiscGetCompanySearchOK{}
}

/*
MiscGetCompanySearchOK describes a response with status code 200, with default header values.

Search a company based on any keyword
*/
type MiscGetCompanySearchOK struct {
	Payload *model.CompanySearchResult
}

// IsSuccess returns true when this misc get company search o k response has a 2xx status code
func (o *MiscGetCompanySearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this misc get company search o k response has a 3xx status code
func (o *MiscGetCompanySearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this misc get company search o k response has a 4xx status code
func (o *MiscGetCompanySearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this misc get company search o k response has a 5xx status code
func (o *MiscGetCompanySearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this misc get company search o k response a status code equal to that given
func (o *MiscGetCompanySearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the misc get company search o k response
func (o *MiscGetCompanySearchOK) Code() int {
	return 200
}

func (o *MiscGetCompanySearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/misc/companysearch/{Keywords}][%d] miscGetCompanySearchOK %s", 200, payload)
}

func (o *MiscGetCompanySearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/misc/companysearch/{Keywords}][%d] miscGetCompanySearchOK %s", 200, payload)
}

func (o *MiscGetCompanySearchOK) GetPayload() *model.CompanySearchResult {
	return o.Payload
}

func (o *MiscGetCompanySearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.CompanySearchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
