// Code generated by go-swagger; DO NOT EDIT.

package financial_transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// FinancialTransactionGetBankTransactionsReader is a Reader for the FinancialTransactionGetBankTransactions structure.
type FinancialTransactionGetBankTransactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FinancialTransactionGetBankTransactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFinancialTransactionGetBankTransactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/financialTransactions] FinancialTransaction_GetBankTransactions", response, response.Code())
	}
}

// NewFinancialTransactionGetBankTransactionsOK creates a FinancialTransactionGetBankTransactionsOK with default headers values
func NewFinancialTransactionGetBankTransactionsOK() *FinancialTransactionGetBankTransactionsOK {
	return &FinancialTransactionGetBankTransactionsOK{}
}

/*
FinancialTransactionGetBankTransactionsOK describes a response with status code 200, with default header values.

FinancialTransactionGetBankTransactionsOK financial transaction get bank transactions o k
*/
type FinancialTransactionGetBankTransactionsOK struct {
}

// IsSuccess returns true when this financial transaction get bank transactions o k response has a 2xx status code
func (o *FinancialTransactionGetBankTransactionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this financial transaction get bank transactions o k response has a 3xx status code
func (o *FinancialTransactionGetBankTransactionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this financial transaction get bank transactions o k response has a 4xx status code
func (o *FinancialTransactionGetBankTransactionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this financial transaction get bank transactions o k response has a 5xx status code
func (o *FinancialTransactionGetBankTransactionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this financial transaction get bank transactions o k response a status code equal to that given
func (o *FinancialTransactionGetBankTransactionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the financial transaction get bank transactions o k response
func (o *FinancialTransactionGetBankTransactionsOK) Code() int {
	return 200
}

func (o *FinancialTransactionGetBankTransactionsOK) Error() string {
	return fmt.Sprintf("[GET /v1/financialTransactions][%d] financialTransactionGetBankTransactionsOK", 200)
}

func (o *FinancialTransactionGetBankTransactionsOK) String() string {
	return fmt.Sprintf("[GET /v1/financialTransactions][%d] financialTransactionGetBankTransactionsOK", 200)
}

func (o *FinancialTransactionGetBankTransactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
