// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountRegistrationResponse account registration response
//
// swagger:model AccountRegistrationResponse
type AccountRegistrationResponse struct {

	// registration ID
	RegistrationID int32 `json:"RegistrationID,omitempty"`
}

// Validate validates this account registration response
func (m *AccountRegistrationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this account registration response based on context it is used
func (m *AccountRegistrationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountRegistrationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountRegistrationResponse) UnmarshalBinary(b []byte) error {
	var res AccountRegistrationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
