// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddNewLicenseBillableModel add new license billable model
//
// swagger:model AddNewLicenseBillableModel
type AddNewLicenseBillableModel struct {

	// amount of extra documents
	AmountOfExtraDocuments int32 `json:"AmountOfExtraDocuments,omitempty"`

	// amount of extra users
	AmountOfExtraUsers int32 `json:"AmountOfExtraUsers,omitempty"`

	// company ID
	CompanyID int32 `json:"CompanyID,omitempty"`
}

// Validate validates this add new license billable model
func (m *AddNewLicenseBillableModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add new license billable model based on context it is used
func (m *AddNewLicenseBillableModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddNewLicenseBillableModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddNewLicenseBillableModel) UnmarshalBinary(b []byte) error {
	var res AddNewLicenseBillableModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
