// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdditionalDocuments additional documents
//
// swagger:model AdditionalDocuments
type AdditionalDocuments struct {

	// attachment
	Attachment *File `json:"Attachment,omitempty"`

	// custom fields
	CustomFields map[string]string `json:"CustomFields,omitempty"`

	// document description
	DocumentDescription string `json:"DocumentDescription,omitempty"`

	// document type
	DocumentType string `json:"DocumentType,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`
}

// Validate validates this additional documents
func (m *AdditionalDocuments) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttachment(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdditionalDocuments) validateAttachment(formats strfmt.Registry) error {
	if swag.IsZero(m.Attachment) { // not required
		return nil
	}

	if m.Attachment != nil {
		if err := m.Attachment.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Attachment")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Attachment")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this additional documents based on the context it is used
func (m *AdditionalDocuments) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAttachment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdditionalDocuments) contextValidateAttachment(ctx context.Context, formats strfmt.Registry) error {

	if m.Attachment != nil {

		if swag.IsZero(m.Attachment) { // not required
			return nil
		}

		if err := m.Attachment.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Attachment")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Attachment")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AdditionalDocuments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdditionalDocuments) UnmarshalBinary(b []byte) error {
	var res AdditionalDocuments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
