// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BookingEntry booking entry
//
// swagger:model BookingEntry
type BookingEntry struct {

	// account code
	AccountCode int32 `json:"AccountCode,omitempty"`

	// amount
	Amount float64 `json:"Amount,omitempty"`

	// booking entry ID
	BookingEntryID int32 `json:"BookingEntryID,omitempty"`

	// debet or credit
	DebetOrCredit string `json:"DebetOrCredit,omitempty"`

	// order ID
	OrderID int32 `json:"OrderID,omitempty"`

	// v a t1
	VAT1 int32 `json:"VAT1,omitempty"`

	// v a t2
	VAT2 int32 `json:"VAT2,omitempty"`

	// v a t3
	VAT3 int32 `json:"VAT3,omitempty"`
}

// Validate validates this booking entry
func (m *BookingEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this booking entry based on context it is used
func (m *BookingEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BookingEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BookingEntry) UnmarshalBinary(b []byte) error {
	var res BookingEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
