// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Cashbook cashbook
//
// swagger:model Cashbook
type Cashbook struct {

	// cashbook ID
	CashbookID int32 `json:"CashbookID,omitempty"`

	// closed
	Closed bool `json:"Closed,omitempty"`

	// from date
	// Format: date-time
	FromDate strfmt.DateTime `json:"FromDate,omitempty"`
}

// Validate validates this cashbook
func (m *Cashbook) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFromDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Cashbook) validateFromDate(formats strfmt.Registry) error {
	if swag.IsZero(m.FromDate) { // not required
		return nil
	}

	if err := validate.FormatOf("FromDate", "body", "date-time", m.FromDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this cashbook based on context it is used
func (m *Cashbook) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Cashbook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Cashbook) UnmarshalBinary(b []byte) error {
	var res Cashbook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
