// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfirmRequest Optional, For logging purpose
//
// swagger:model ConfirmRequest
type ConfirmRequest struct {

	// remote path
	RemotePath string `json:"RemotePath,omitempty"`

	// remote server name
	RemoteServerName string `json:"RemoteServerName,omitempty"`
}

// Validate validates this confirm request
func (m *ConfirmRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this confirm request based on context it is used
func (m *ConfirmRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfirmRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfirmRequest) UnmarshalBinary(b []byte) error {
	var res ConfirmRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
