// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DailyReceiptBookEntryModel daily receipt book entry model
//
// swagger:model DailyReceiptBookEntryModel
type DailyReceiptBookEntryModel struct {

	// description
	Description string `json:"Description,omitempty"`

	// input date
	// Format: date-time
	InputDate strfmt.DateTime `json:"InputDate,omitempty"`

	// total incl
	TotalIncl float64 `json:"TotalIncl,omitempty"`

	// v a t percentage
	VATPercentage float64 `json:"VATPercentage,omitempty"`

	// ventilation code t c
	VentilationCodeTC string `json:"VentilationCodeTC,omitempty"`
}

// Validate validates this daily receipt book entry model
func (m *DailyReceiptBookEntryModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInputDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DailyReceiptBookEntryModel) validateInputDate(formats strfmt.Registry) error {
	if swag.IsZero(m.InputDate) { // not required
		return nil
	}

	if err := validate.FormatOf("InputDate", "body", "date-time", m.InputDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this daily receipt book entry model based on context it is used
func (m *DailyReceiptBookEntryModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DailyReceiptBookEntryModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DailyReceiptBookEntryModel) UnmarshalBinary(b []byte) error {
	var res DailyReceiptBookEntryModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
