// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DailyReceiptBookModelResponseModel daily receipt book model response model
//
// swagger:model DailyReceiptBookModelResponseModel
type DailyReceiptBookModelResponseModel struct {

	// cashbook entries
	CashbookEntries []*GetDailyReceiptEntryResponseModel `json:"CashbookEntries"`

	// cashbooks
	Cashbooks []*Cashbook `json:"Cashbooks"`
}

// Validate validates this daily receipt book model response model
func (m *DailyReceiptBookModelResponseModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCashbookEntries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCashbooks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DailyReceiptBookModelResponseModel) validateCashbookEntries(formats strfmt.Registry) error {
	if swag.IsZero(m.CashbookEntries) { // not required
		return nil
	}

	for i := 0; i < len(m.CashbookEntries); i++ {
		if swag.IsZero(m.CashbookEntries[i]) { // not required
			continue
		}

		if m.CashbookEntries[i] != nil {
			if err := m.CashbookEntries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("CashbookEntries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("CashbookEntries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DailyReceiptBookModelResponseModel) validateCashbooks(formats strfmt.Registry) error {
	if swag.IsZero(m.Cashbooks) { // not required
		return nil
	}

	for i := 0; i < len(m.Cashbooks); i++ {
		if swag.IsZero(m.Cashbooks[i]) { // not required
			continue
		}

		if m.Cashbooks[i] != nil {
			if err := m.Cashbooks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Cashbooks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Cashbooks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this daily receipt book model response model based on the context it is used
func (m *DailyReceiptBookModelResponseModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCashbookEntries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCashbooks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DailyReceiptBookModelResponseModel) contextValidateCashbookEntries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CashbookEntries); i++ {

		if m.CashbookEntries[i] != nil {

			if swag.IsZero(m.CashbookEntries[i]) { // not required
				return nil
			}

			if err := m.CashbookEntries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("CashbookEntries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("CashbookEntries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DailyReceiptBookModelResponseModel) contextValidateCashbooks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Cashbooks); i++ {

		if m.Cashbooks[i] != nil {

			if swag.IsZero(m.Cashbooks[i]) { // not required
				return nil
			}

			if err := m.Cashbooks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Cashbooks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Cashbooks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DailyReceiptBookModelResponseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DailyReceiptBookModelResponseModel) UnmarshalBinary(b []byte) error {
	var res DailyReceiptBookModelResponseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
