// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteParticipantRequest delete participant request
//
// swagger:model DeleteParticipantRequest
type DeleteParticipantRequest struct {

	// company ID
	CompanyID string `json:"CompanyID,omitempty"`
}

// Validate validates this delete participant request
func (m *DeleteParticipantRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete participant request based on context it is used
func (m *DeleteParticipantRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteParticipantRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteParticipantRequest) UnmarshalBinary(b []byte) error {
	var res DeleteParticipantRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
