// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EinvoiceRegistrationsAccount einvoice registrations account
//
// swagger:model EinvoiceRegistrationsAccount
type EinvoiceRegistrationsAccount struct {

	// company details
	CompanyDetails *EinvoiceRegistrationPost `json:"CompanyDetails,omitempty"`

	// integrations
	Integrations []*EinvoiceIntegration `json:"Integrations"`

	// registration ID
	RegistrationID int32 `json:"RegistrationID,omitempty"`
}

// Validate validates this einvoice registrations account
func (m *EinvoiceRegistrationsAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompanyDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIntegrations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EinvoiceRegistrationsAccount) validateCompanyDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.CompanyDetails) { // not required
		return nil
	}

	if m.CompanyDetails != nil {
		if err := m.CompanyDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("CompanyDetails")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("CompanyDetails")
			}
			return err
		}
	}

	return nil
}

func (m *EinvoiceRegistrationsAccount) validateIntegrations(formats strfmt.Registry) error {
	if swag.IsZero(m.Integrations) { // not required
		return nil
	}

	for i := 0; i < len(m.Integrations); i++ {
		if swag.IsZero(m.Integrations[i]) { // not required
			continue
		}

		if m.Integrations[i] != nil {
			if err := m.Integrations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Integrations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Integrations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this einvoice registrations account based on the context it is used
func (m *EinvoiceRegistrationsAccount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompanyDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIntegrations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EinvoiceRegistrationsAccount) contextValidateCompanyDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.CompanyDetails != nil {

		if swag.IsZero(m.CompanyDetails) { // not required
			return nil
		}

		if err := m.CompanyDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("CompanyDetails")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("CompanyDetails")
			}
			return err
		}
	}

	return nil
}

func (m *EinvoiceRegistrationsAccount) contextValidateIntegrations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Integrations); i++ {

		if m.Integrations[i] != nil {

			if swag.IsZero(m.Integrations[i]) { // not required
				return nil
			}

			if err := m.Integrations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Integrations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Integrations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EinvoiceRegistrationsAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EinvoiceRegistrationsAccount) UnmarshalBinary(b []byte) error {
	var res EinvoiceRegistrationsAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
