// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EinvoiceIntegration einvoice integration
//
// swagger:model EinvoiceIntegration
type EinvoiceIntegration struct {

	// integration
	Integration string `json:"Integration,omitempty"`

	// integration document to sign
	IntegrationDocumentToSign string `json:"IntegrationDocumentToSign,omitempty"`

	// integration ID
	IntegrationID int32 `json:"IntegrationID,omitempty"`

	// integration status
	IntegrationStatus string `json:"IntegrationStatus,omitempty"`

	// integration status description
	IntegrationStatusDescription string `json:"IntegrationStatusDescription,omitempty"`
}

// Validate validates this einvoice integration
func (m *EinvoiceIntegration) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this einvoice integration based on context it is used
func (m *EinvoiceIntegration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EinvoiceIntegration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EinvoiceIntegration) UnmarshalBinary(b []byte) error {
	var res EinvoiceIntegration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
