// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// File file
//
// swagger:model File
type File struct {

	// file content
	// Format: byte
	FileContent strfmt.Base64 `json:"FileContent,omitempty"`

	// file ID
	// Example: 00000000-0000-0000-0000-000000000000
	// Format: uuid
	FileID strfmt.UUID `json:"FileID,omitempty"`

	// file name
	FileName string `json:"FileName,omitempty"`

	// mime type
	MimeType string `json:"MimeType,omitempty"`
}

// Validate validates this file
func (m *File) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFileID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *File) validateFileID(formats strfmt.Registry) error {
	if swag.IsZero(m.FileID) { // not required
		return nil
	}

	if err := validate.FormatOf("FileID", "body", "uuid", m.FileID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this file based on context it is used
func (m *File) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *File) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *File) UnmarshalBinary(b []byte) error {
	var res File
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
