// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IEdmVocabularyAnnotation i edm vocabulary annotation
//
// swagger:model IEdmVocabularyAnnotation
type IEdmVocabularyAnnotation struct {

	// qualifier
	// Read Only: true
	Qualifier string `json:"Qualifier,omitempty"`

	// target
	// Read Only: true
	Target IEdmVocabularyAnnotatable `json:"Target,omitempty"`

	// term
	// Read Only: true
	Term *IEdmTerm `json:"Term,omitempty"`
}

// Validate validates this i edm vocabulary annotation
func (m *IEdmVocabularyAnnotation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTerm(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IEdmVocabularyAnnotation) validateTerm(formats strfmt.Registry) error {
	if swag.IsZero(m.Term) { // not required
		return nil
	}

	if m.Term != nil {
		if err := m.Term.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Term")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Term")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this i edm vocabulary annotation based on the context it is used
func (m *IEdmVocabularyAnnotation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateQualifier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTerm(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IEdmVocabularyAnnotation) contextValidateQualifier(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "Qualifier", "body", string(m.Qualifier)); err != nil {
		return err
	}

	return nil
}

func (m *IEdmVocabularyAnnotation) contextValidateTerm(ctx context.Context, formats strfmt.Registry) error {

	if m.Term != nil {

		if swag.IsZero(m.Term) { // not required
			return nil
		}

		if err := m.Term.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Term")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Term")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IEdmVocabularyAnnotation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IEdmVocabularyAnnotation) UnmarshalBinary(b []byte) error {
	var res IEdmVocabularyAnnotation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
