// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PartyIdentifier party identifier
//
// swagger:model PartyIdentifier
type PartyIdentifier struct {

	// identifier
	Identifier string `json:"Identifier,omitempty"`

	// identifier type
	IdentifierType string `json:"IdentifierType,omitempty"`

	// preferred
	Preferred bool `json:"Preferred,omitempty"`

	// scheme ID
	SchemeID string `json:"SchemeID,omitempty"`
}

// Validate validates this party identifier
func (m *PartyIdentifier) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this party identifier based on context it is used
func (m *PartyIdentifier) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PartyIdentifier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartyIdentifier) UnmarshalBinary(b []byte) error {
	var res PartyIdentifier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
