// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentLink payment link
//
// swagger:model PaymentLink
type PaymentLink struct {

	// click Url
	ClickURL string `json:"ClickUrl,omitempty"`

	// external provider
	ExternalProvider string `json:"ExternalProvider,omitempty"`

	// q r image Url
	QRImageURL string `json:"QRImageUrl,omitempty"`
}

// Validate validates this payment link
func (m *PaymentLink) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment link based on context it is used
func (m *PaymentLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentLink) UnmarshalBinary(b []byte) error {
	var res PaymentLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
