// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SelectExpandClause select expand clause
//
// swagger:model SelectExpandClause
type SelectExpandClause struct {

	// all selected
	// Read Only: true
	AllSelected *bool `json:"AllSelected,omitempty"`

	// selected items
	// Read Only: true
	SelectedItems []SelectItem `json:"SelectedItems"`
}

// Validate validates this select expand clause
func (m *SelectExpandClause) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this select expand clause based on the context it is used
func (m *SelectExpandClause) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAllSelected(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSelectedItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SelectExpandClause) contextValidateAllSelected(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "AllSelected", "body", m.AllSelected); err != nil {
		return err
	}

	return nil
}

func (m *SelectExpandClause) contextValidateSelectedItems(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "SelectedItems", "body", []SelectItem(m.SelectedItems)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SelectExpandClause) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SelectExpandClause) UnmarshalBinary(b []byte) error {
	var res SelectExpandClause
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
