// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateLicenseRequestModel update license request model
//
// swagger:model UpdateLicenseRequestModel
type UpdateLicenseRequestModel struct {

	// company ID
	CompanyID int32 `json:"CompanyID,omitempty"`

	// license
	License *LicenseConfiguration `json:"License,omitempty"`
}

// Validate validates this update license request model
func (m *UpdateLicenseRequestModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLicense(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateLicenseRequestModel) validateLicense(formats strfmt.Registry) error {
	if swag.IsZero(m.License) { // not required
		return nil
	}

	if m.License != nil {
		if err := m.License.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("License")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("License")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this update license request model based on the context it is used
func (m *UpdateLicenseRequestModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLicense(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateLicenseRequestModel) contextValidateLicense(ctx context.Context, formats strfmt.Registry) error {

	if m.License != nil {

		if swag.IsZero(m.License) { // not required
			return nil
		}

		if err := m.License.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("License")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("License")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateLicenseRequestModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateLicenseRequestModel) UnmarshalBinary(b []byte) error {
	var res UpdateLicenseRequestModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
