// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VatGroup vat group
//
// swagger:model VatGroup
type VatGroup struct {

	// financial reduction amount
	FinancialReductionAmount float64 `json:"FinancialReductionAmount,omitempty"`

	// mtvh
	Mtvh float64 `json:"Mtvh,omitempty"`

	// total excl
	TotalExcl float64 `json:"TotalExcl,omitempty"`

	// total incl
	TotalIncl float64 `json:"TotalIncl,omitempty"`

	// total v a t
	TotalVAT float64 `json:"TotalVAT,omitempty"`

	// v a t percentage
	VATPercentage float64 `json:"VATPercentage,omitempty"`

	// ventilation code
	VentilationCode string `json:"VentilationCode,omitempty"`
}

// Validate validates this vat group
func (m *VatGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vat group based on context it is used
func (m *VatGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VatGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VatGroup) UnmarshalBinary(b []byte) error {
	var res VatGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
