// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Webhook webhook
//
// swagger:model Webhook
type Webhook struct {

	// company ID
	CompanyID int32 `json:"CompanyID,omitempty"`

	// entity type
	EntityType string `json:"EntityType,omitempty"`

	// entity update type
	EntityUpdateType string `json:"EntityUpdateType,omitempty"`

	// secret
	Secret string `json:"Secret,omitempty"`

	// user ID
	UserID int32 `json:"UserID,omitempty"`

	// webhook ID
	WebhookID int32 `json:"WebhookID,omitempty"`

	// webhook URL
	WebhookURL string `json:"WebhookURL,omitempty"`
}

// Validate validates this webhook
func (m *Webhook) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this webhook based on context it is used
func (m *Webhook) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Webhook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Webhook) UnmarshalBinary(b []byte) error {
	var res Webhook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
