// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// ReportReportDetailGetReader is a Reader for the ReportReportDetailGet structure.
type ReportReportDetailGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReportReportDetailGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReportReportDetailGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/reports/{reportID}] Report_ReportDetailGet", response, response.Code())
	}
}

// NewReportReportDetailGetOK creates a ReportReportDetailGetOK with default headers values
func NewReportReportDetailGetOK() *ReportReportDetailGetOK {
	return &ReportReportDetailGetOK{}
}

/*
ReportReportDetailGetOK describes a response with status code 200, with default header values.

Returns the result and name of the report specified by the reportID
*/
type ReportReportDetailGetOK struct {
	Payload *model.ReportDetailModel
}

// IsSuccess returns true when this report report detail get o k response has a 2xx status code
func (o *ReportReportDetailGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this report report detail get o k response has a 3xx status code
func (o *ReportReportDetailGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this report report detail get o k response has a 4xx status code
func (o *ReportReportDetailGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this report report detail get o k response has a 5xx status code
func (o *ReportReportDetailGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this report report detail get o k response a status code equal to that given
func (o *ReportReportDetailGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the report report detail get o k response
func (o *ReportReportDetailGetOK) Code() int {
	return 200
}

func (o *ReportReportDetailGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/reports/{reportID}][%d] reportReportDetailGetOK %s", 200, payload)
}

func (o *ReportReportDetailGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/reports/{reportID}][%d] reportReportDetailGetOK %s", 200, payload)
}

func (o *ReportReportDetailGetOK) GetPayload() *model.ReportDetailModel {
	return o.Payload
}

func (o *ReportReportDetailGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ReportDetailModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
