// Code generated by go-swagger; DO NOT EDIT.

package accountant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAccountantGetFeedsParams creates a new AccountantGetFeedsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAccountantGetFeedsParams() *AccountantGetFeedsParams {
	return &AccountantGetFeedsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAccountantGetFeedsParamsWithTimeout creates a new AccountantGetFeedsParams object
// with the ability to set a timeout on a request.
func NewAccountantGetFeedsParamsWithTimeout(timeout time.Duration) *AccountantGetFeedsParams {
	return &AccountantGetFeedsParams{
		timeout: timeout,
	}
}

// NewAccountantGetFeedsParamsWithContext creates a new AccountantGetFeedsParams object
// with the ability to set a context for a request.
func NewAccountantGetFeedsParamsWithContext(ctx context.Context) *AccountantGetFeedsParams {
	return &AccountantGetFeedsParams{
		Context: ctx,
	}
}

// NewAccountantGetFeedsParamsWithHTTPClient creates a new AccountantGetFeedsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAccountantGetFeedsParamsWithHTTPClient(client *http.Client) *AccountantGetFeedsParams {
	return &AccountantGetFeedsParams{
		HTTPClient: client,
	}
}

/*
AccountantGetFeedsParams contains all the parameters to send to the API endpoint

	for the accountant get feeds operation.

	Typically these are written to a http.Request.
*/
type AccountantGetFeedsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the accountant get feeds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AccountantGetFeedsParams) WithDefaults() *AccountantGetFeedsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the accountant get feeds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AccountantGetFeedsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the accountant get feeds params
func (o *AccountantGetFeedsParams) WithTimeout(timeout time.Duration) *AccountantGetFeedsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accountant get feeds params
func (o *AccountantGetFeedsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accountant get feeds params
func (o *AccountantGetFeedsParams) WithContext(ctx context.Context) *AccountantGetFeedsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accountant get feeds params
func (o *AccountantGetFeedsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accountant get feeds params
func (o *AccountantGetFeedsParams) WithHTTPClient(client *http.Client) *AccountantGetFeedsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accountant get feeds params
func (o *AccountantGetFeedsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AccountantGetFeedsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
