// Code generated by go-swagger; DO NOT EDIT.

package journal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewJournalPostGLAccountParams creates a new JournalPostGLAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewJournalPostGLAccountParams() *JournalPostGLAccountParams {
	return &JournalPostGLAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewJournalPostGLAccountParamsWithTimeout creates a new JournalPostGLAccountParams object
// with the ability to set a timeout on a request.
func NewJournalPostGLAccountParamsWithTimeout(timeout time.Duration) *JournalPostGLAccountParams {
	return &JournalPostGLAccountParams{
		timeout: timeout,
	}
}

// NewJournalPostGLAccountParamsWithContext creates a new JournalPostGLAccountParams object
// with the ability to set a context for a request.
func NewJournalPostGLAccountParamsWithContext(ctx context.Context) *JournalPostGLAccountParams {
	return &JournalPostGLAccountParams{
		Context: ctx,
	}
}

// NewJournalPostGLAccountParamsWithHTTPClient creates a new JournalPostGLAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewJournalPostGLAccountParamsWithHTTPClient(client *http.Client) *JournalPostGLAccountParams {
	return &JournalPostGLAccountParams{
		HTTPClient: client,
	}
}

/*
JournalPostGLAccountParams contains all the parameters to send to the API endpoint

	for the journal post g l account operation.

	Typically these are written to a http.Request.
*/
type JournalPostGLAccountParams struct {

	// Journals.
	Journals []*model.Journal

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the journal post g l account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JournalPostGLAccountParams) WithDefaults() *JournalPostGLAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the journal post g l account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JournalPostGLAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the journal post g l account params
func (o *JournalPostGLAccountParams) WithTimeout(timeout time.Duration) *JournalPostGLAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the journal post g l account params
func (o *JournalPostGLAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the journal post g l account params
func (o *JournalPostGLAccountParams) WithContext(ctx context.Context) *JournalPostGLAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the journal post g l account params
func (o *JournalPostGLAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the journal post g l account params
func (o *JournalPostGLAccountParams) WithHTTPClient(client *http.Client) *JournalPostGLAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the journal post g l account params
func (o *JournalPostGLAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJournals adds the journals to the journal post g l account params
func (o *JournalPostGLAccountParams) WithJournals(journals []*model.Journal) *JournalPostGLAccountParams {
	o.SetJournals(journals)
	return o
}

// SetJournals adds the journals to the journal post g l account params
func (o *JournalPostGLAccountParams) SetJournals(journals []*model.Journal) {
	o.Journals = journals
}

// WriteToRequest writes these params to a swagger request
func (o *JournalPostGLAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Journals != nil {
		if err := r.SetBodyParam(o.Journals); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
