// Code generated by go-swagger; DO NOT EDIT.

package journal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// JournalPostGLAccountReader is a Reader for the JournalPostGLAccount structure.
type JournalPostGLAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JournalPostGLAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJournalPostGLAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/journals/commands/import] Journal_PostGLAccount", response, response.Code())
	}
}

// NewJournalPostGLAccountOK creates a JournalPostGLAccountOK with default headers values
func NewJournalPostGLAccountOK() *JournalPostGLAccountOK {
	return &JournalPostGLAccountOK{}
}

/*
JournalPostGLAccountOK describes a response with status code 200, with default header values.

Import a list of journals
*/
type JournalPostGLAccountOK struct {
	Payload int32
}

// IsSuccess returns true when this journal post g l account o k response has a 2xx status code
func (o *JournalPostGLAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this journal post g l account o k response has a 3xx status code
func (o *JournalPostGLAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this journal post g l account o k response has a 4xx status code
func (o *JournalPostGLAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this journal post g l account o k response has a 5xx status code
func (o *JournalPostGLAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this journal post g l account o k response a status code equal to that given
func (o *JournalPostGLAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the journal post g l account o k response
func (o *JournalPostGLAccountOK) Code() int {
	return 200
}

func (o *JournalPostGLAccountOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/journals/commands/import][%d] journalPostGLAccountOK %s", 200, payload)
}

func (o *JournalPostGLAccountOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/journals/commands/import][%d] journalPostGLAccountOK %s", 200, payload)
}

func (o *JournalPostGLAccountOK) GetPayload() int32 {
	return o.Payload
}

func (o *JournalPostGLAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
