// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewOrderPatchOrdersParams creates a new OrderPatchOrdersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderPatchOrdersParams() *OrderPatchOrdersParams {
	return &OrderPatchOrdersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderPatchOrdersParamsWithTimeout creates a new OrderPatchOrdersParams object
// with the ability to set a timeout on a request.
func NewOrderPatchOrdersParamsWithTimeout(timeout time.Duration) *OrderPatchOrdersParams {
	return &OrderPatchOrdersParams{
		timeout: timeout,
	}
}

// NewOrderPatchOrdersParamsWithContext creates a new OrderPatchOrdersParams object
// with the ability to set a context for a request.
func NewOrderPatchOrdersParamsWithContext(ctx context.Context) *OrderPatchOrdersParams {
	return &OrderPatchOrdersParams{
		Context: ctx,
	}
}

// NewOrderPatchOrdersParamsWithHTTPClient creates a new OrderPatchOrdersParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderPatchOrdersParamsWithHTTPClient(client *http.Client) *OrderPatchOrdersParams {
	return &OrderPatchOrdersParams{
		HTTPClient: client,
	}
}

/*
OrderPatchOrdersParams contains all the parameters to send to the API endpoint

	for the order patch orders operation.

	Typically these are written to a http.Request.
*/
type OrderPatchOrdersParams struct {

	// Delta.
	Delta interface{}

	// OrderID.
	//
	// Format: int32
	OrderID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the order patch orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderPatchOrdersParams) WithDefaults() *OrderPatchOrdersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the order patch orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderPatchOrdersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the order patch orders params
func (o *OrderPatchOrdersParams) WithTimeout(timeout time.Duration) *OrderPatchOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order patch orders params
func (o *OrderPatchOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order patch orders params
func (o *OrderPatchOrdersParams) WithContext(ctx context.Context) *OrderPatchOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order patch orders params
func (o *OrderPatchOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order patch orders params
func (o *OrderPatchOrdersParams) WithHTTPClient(client *http.Client) *OrderPatchOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order patch orders params
func (o *OrderPatchOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelta adds the delta to the order patch orders params
func (o *OrderPatchOrdersParams) WithDelta(delta interface{}) *OrderPatchOrdersParams {
	o.SetDelta(delta)
	return o
}

// SetDelta adds the delta to the order patch orders params
func (o *OrderPatchOrdersParams) SetDelta(delta interface{}) {
	o.Delta = delta
}

// WithOrderID adds the orderID to the order patch orders params
func (o *OrderPatchOrdersParams) WithOrderID(orderID int32) *OrderPatchOrdersParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the order patch orders params
func (o *OrderPatchOrdersParams) SetOrderID(orderID int32) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *OrderPatchOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Delta != nil {
		if err := r.SetBodyParam(o.Delta); err != nil {
			return err
		}
	}

	// path param orderID
	if err := r.SetPathParam("orderID", swag.FormatInt32(o.OrderID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
