// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/becoded/billit/model"
)

// NewOrderPutOrderBookingsParams creates a new OrderPutOrderBookingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderPutOrderBookingsParams() *OrderPutOrderBookingsParams {
	return &OrderPutOrderBookingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderPutOrderBookingsParamsWithTimeout creates a new OrderPutOrderBookingsParams object
// with the ability to set a timeout on a request.
func NewOrderPutOrderBookingsParamsWithTimeout(timeout time.Duration) *OrderPutOrderBookingsParams {
	return &OrderPutOrderBookingsParams{
		timeout: timeout,
	}
}

// NewOrderPutOrderBookingsParamsWithContext creates a new OrderPutOrderBookingsParams object
// with the ability to set a context for a request.
func NewOrderPutOrderBookingsParamsWithContext(ctx context.Context) *OrderPutOrderBookingsParams {
	return &OrderPutOrderBookingsParams{
		Context: ctx,
	}
}

// NewOrderPutOrderBookingsParamsWithHTTPClient creates a new OrderPutOrderBookingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderPutOrderBookingsParamsWithHTTPClient(client *http.Client) *OrderPutOrderBookingsParams {
	return &OrderPutOrderBookingsParams{
		HTTPClient: client,
	}
}

/*
OrderPutOrderBookingsParams contains all the parameters to send to the API endpoint

	for the order put order bookings operation.

	Typically these are written to a http.Request.
*/
type OrderPutOrderBookingsParams struct {

	// BookingEntries.
	BookingEntries []*model.BookingEntry

	// OrderID.
	//
	// Format: int32
	OrderID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the order put order bookings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderPutOrderBookingsParams) WithDefaults() *OrderPutOrderBookingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the order put order bookings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderPutOrderBookingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the order put order bookings params
func (o *OrderPutOrderBookingsParams) WithTimeout(timeout time.Duration) *OrderPutOrderBookingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order put order bookings params
func (o *OrderPutOrderBookingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order put order bookings params
func (o *OrderPutOrderBookingsParams) WithContext(ctx context.Context) *OrderPutOrderBookingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order put order bookings params
func (o *OrderPutOrderBookingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order put order bookings params
func (o *OrderPutOrderBookingsParams) WithHTTPClient(client *http.Client) *OrderPutOrderBookingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order put order bookings params
func (o *OrderPutOrderBookingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBookingEntries adds the bookingEntries to the order put order bookings params
func (o *OrderPutOrderBookingsParams) WithBookingEntries(bookingEntries []*model.BookingEntry) *OrderPutOrderBookingsParams {
	o.SetBookingEntries(bookingEntries)
	return o
}

// SetBookingEntries adds the bookingEntries to the order put order bookings params
func (o *OrderPutOrderBookingsParams) SetBookingEntries(bookingEntries []*model.BookingEntry) {
	o.BookingEntries = bookingEntries
}

// WithOrderID adds the orderID to the order put order bookings params
func (o *OrderPutOrderBookingsParams) WithOrderID(orderID int32) *OrderPutOrderBookingsParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the order put order bookings params
func (o *OrderPutOrderBookingsParams) SetOrderID(orderID int32) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *OrderPutOrderBookingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.BookingEntries != nil {
		if err := r.SetBodyParam(o.BookingEntries); err != nil {
			return err
		}
	}

	// path param orderID
	if err := r.SetPathParam("orderID", swag.FormatInt32(o.OrderID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
