// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrderGetDeletedParams creates a new OrderGetDeletedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderGetDeletedParams() *OrderGetDeletedParams {
	return &OrderGetDeletedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderGetDeletedParamsWithTimeout creates a new OrderGetDeletedParams object
// with the ability to set a timeout on a request.
func NewOrderGetDeletedParamsWithTimeout(timeout time.Duration) *OrderGetDeletedParams {
	return &OrderGetDeletedParams{
		timeout: timeout,
	}
}

// NewOrderGetDeletedParamsWithContext creates a new OrderGetDeletedParams object
// with the ability to set a context for a request.
func NewOrderGetDeletedParamsWithContext(ctx context.Context) *OrderGetDeletedParams {
	return &OrderGetDeletedParams{
		Context: ctx,
	}
}

// NewOrderGetDeletedParamsWithHTTPClient creates a new OrderGetDeletedParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderGetDeletedParamsWithHTTPClient(client *http.Client) *OrderGetDeletedParams {
	return &OrderGetDeletedParams{
		HTTPClient: client,
	}
}

/*
OrderGetDeletedParams contains all the parameters to send to the API endpoint

	for the order get deleted operation.

	Typically these are written to a http.Request.
*/
type OrderGetDeletedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the order get deleted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderGetDeletedParams) WithDefaults() *OrderGetDeletedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the order get deleted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderGetDeletedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the order get deleted params
func (o *OrderGetDeletedParams) WithTimeout(timeout time.Duration) *OrderGetDeletedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order get deleted params
func (o *OrderGetDeletedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order get deleted params
func (o *OrderGetDeletedParams) WithContext(ctx context.Context) *OrderGetDeletedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order get deleted params
func (o *OrderGetDeletedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order get deleted params
func (o *OrderGetDeletedParams) WithHTTPClient(client *http.Client) *OrderGetDeletedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order get deleted params
func (o *OrderGetDeletedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OrderGetDeletedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
