// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrderGetDeletedReader is a Reader for the OrderGetDeleted structure.
type OrderGetDeletedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrderGetDeletedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrderGetDeletedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/orders/deleted] Order_GetDeleted", response, response.Code())
	}
}

// NewOrderGetDeletedOK creates a OrderGetDeletedOK with default headers values
func NewOrderGetDeletedOK() *OrderGetDeletedOK {
	return &OrderGetDeletedOK{}
}

/*
OrderGetDeletedOK describes a response with status code 200, with default header values.

All orders have been sent
*/
type OrderGetDeletedOK struct {
}

// IsSuccess returns true when this order get deleted o k response has a 2xx status code
func (o *OrderGetDeletedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this order get deleted o k response has a 3xx status code
func (o *OrderGetDeletedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this order get deleted o k response has a 4xx status code
func (o *OrderGetDeletedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this order get deleted o k response has a 5xx status code
func (o *OrderGetDeletedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this order get deleted o k response a status code equal to that given
func (o *OrderGetDeletedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the order get deleted o k response
func (o *OrderGetDeletedOK) Code() int {
	return 200
}

func (o *OrderGetDeletedOK) Error() string {
	return fmt.Sprintf("[GET /v1/orders/deleted][%d] orderGetDeletedOK", 200)
}

func (o *OrderGetDeletedOK) String() string {
	return fmt.Sprintf("[GET /v1/orders/deleted][%d] orderGetDeletedOK", 200)
}

func (o *OrderGetDeletedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
