// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OrderESignOrderReader is a Reader for the OrderESignOrder structure.
type OrderESignOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrderESignOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrderESignOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/orders/commands/eSign/{orderID}] Order_ESignOrder", response, response.Code())
	}
}

// NewOrderESignOrderOK creates a OrderESignOrderOK with default headers values
func NewOrderESignOrderOK() *OrderESignOrderOK {
	return &OrderESignOrderOK{}
}

/*
OrderESignOrderOK describes a response with status code 200, with default header values.

E-Sign an order
*/
type OrderESignOrderOK struct {
	Payload int32
}

// IsSuccess returns true when this order e sign order o k response has a 2xx status code
func (o *OrderESignOrderOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this order e sign order o k response has a 3xx status code
func (o *OrderESignOrderOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this order e sign order o k response has a 4xx status code
func (o *OrderESignOrderOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this order e sign order o k response has a 5xx status code
func (o *OrderESignOrderOK) IsServerError() bool {
	return false
}

// IsCode returns true when this order e sign order o k response a status code equal to that given
func (o *OrderESignOrderOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the order e sign order o k response
func (o *OrderESignOrderOK) Code() int {
	return 200
}

func (o *OrderESignOrderOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orders/commands/eSign/{orderID}][%d] orderESignOrderOK %s", 200, payload)
}

func (o *OrderESignOrderOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orders/commands/eSign/{orderID}][%d] orderESignOrderOK %s", 200, payload)
}

func (o *OrderESignOrderOK) GetPayload() int32 {
	return o.Payload
}

func (o *OrderESignOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
