// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewOrderPostSendParams creates a new OrderPostSendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderPostSendParams() *OrderPostSendParams {
	return &OrderPostSendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderPostSendParamsWithTimeout creates a new OrderPostSendParams object
// with the ability to set a timeout on a request.
func NewOrderPostSendParamsWithTimeout(timeout time.Duration) *OrderPostSendParams {
	return &OrderPostSendParams{
		timeout: timeout,
	}
}

// NewOrderPostSendParamsWithContext creates a new OrderPostSendParams object
// with the ability to set a context for a request.
func NewOrderPostSendParamsWithContext(ctx context.Context) *OrderPostSendParams {
	return &OrderPostSendParams{
		Context: ctx,
	}
}

// NewOrderPostSendParamsWithHTTPClient creates a new OrderPostSendParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderPostSendParamsWithHTTPClient(client *http.Client) *OrderPostSendParams {
	return &OrderPostSendParams{
		HTTPClient: client,
	}
}

/*
OrderPostSendParams contains all the parameters to send to the API endpoint

	for the order post send operation.

	Typically these are written to a http.Request.
*/
type OrderPostSendParams struct {

	// SendRequest.
	SendRequest *model.SendRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the order post send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderPostSendParams) WithDefaults() *OrderPostSendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the order post send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderPostSendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the order post send params
func (o *OrderPostSendParams) WithTimeout(timeout time.Duration) *OrderPostSendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order post send params
func (o *OrderPostSendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order post send params
func (o *OrderPostSendParams) WithContext(ctx context.Context) *OrderPostSendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order post send params
func (o *OrderPostSendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order post send params
func (o *OrderPostSendParams) WithHTTPClient(client *http.Client) *OrderPostSendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order post send params
func (o *OrderPostSendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSendRequest adds the sendRequest to the order post send params
func (o *OrderPostSendParams) WithSendRequest(sendRequest *model.SendRequest) *OrderPostSendParams {
	o.SetSendRequest(sendRequest)
	return o
}

// SetSendRequest adds the sendRequest to the order post send params
func (o *OrderPostSendParams) SetSendRequest(sendRequest *model.SendRequest) {
	o.SendRequest = sendRequest
}

// WriteToRequest writes these params to a swagger request
func (o *OrderPostSendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SendRequest != nil {
		if err := r.SetBodyParam(o.SendRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
