// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewOrderESignOrderParams creates a new OrderESignOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderESignOrderParams() *OrderESignOrderParams {
	return &OrderESignOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderESignOrderParamsWithTimeout creates a new OrderESignOrderParams object
// with the ability to set a timeout on a request.
func NewOrderESignOrderParamsWithTimeout(timeout time.Duration) *OrderESignOrderParams {
	return &OrderESignOrderParams{
		timeout: timeout,
	}
}

// NewOrderESignOrderParamsWithContext creates a new OrderESignOrderParams object
// with the ability to set a context for a request.
func NewOrderESignOrderParamsWithContext(ctx context.Context) *OrderESignOrderParams {
	return &OrderESignOrderParams{
		Context: ctx,
	}
}

// NewOrderESignOrderParamsWithHTTPClient creates a new OrderESignOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderESignOrderParamsWithHTTPClient(client *http.Client) *OrderESignOrderParams {
	return &OrderESignOrderParams{
		HTTPClient: client,
	}
}

/*
OrderESignOrderParams contains all the parameters to send to the API endpoint

	for the order e sign order operation.

	Typically these are written to a http.Request.
*/
type OrderESignOrderParams struct {

	// OrderID.
	//
	// Format: int32
	OrderID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the order e sign order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderESignOrderParams) WithDefaults() *OrderESignOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the order e sign order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderESignOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the order e sign order params
func (o *OrderESignOrderParams) WithTimeout(timeout time.Duration) *OrderESignOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the order e sign order params
func (o *OrderESignOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the order e sign order params
func (o *OrderESignOrderParams) WithContext(ctx context.Context) *OrderESignOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the order e sign order params
func (o *OrderESignOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the order e sign order params
func (o *OrderESignOrderParams) WithHTTPClient(client *http.Client) *OrderESignOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the order e sign order params
func (o *OrderESignOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the order e sign order params
func (o *OrderESignOrderParams) WithOrderID(orderID int32) *OrderESignOrderParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the order e sign order params
func (o *OrderESignOrderParams) SetOrderID(orderID int32) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *OrderESignOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orderID
	if err := r.SetPathParam("orderID", swag.FormatInt32(o.OrderID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
