// Code generated by go-swagger; DO NOT EDIT.

package to_process

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ToProcessPostToProcessReader is a Reader for the ToProcessPostToProcess structure.
type ToProcessPostToProcessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ToProcessPostToProcessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewToProcessPostToProcessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/toProcess] ToProcess_PostToProcess", response, response.Code())
	}
}

// NewToProcessPostToProcessOK creates a ToProcessPostToProcessOK with default headers values
func NewToProcessPostToProcessOK() *ToProcessPostToProcessOK {
	return &ToProcessPostToProcessOK{}
}

/*
ToProcessPostToProcessOK describes a response with status code 200, with default header values.

Save a new document to process. Rerturns an upload ID
*/
type ToProcessPostToProcessOK struct {
	Payload int32
}

// IsSuccess returns true when this to process post to process o k response has a 2xx status code
func (o *ToProcessPostToProcessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this to process post to process o k response has a 3xx status code
func (o *ToProcessPostToProcessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this to process post to process o k response has a 4xx status code
func (o *ToProcessPostToProcessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this to process post to process o k response has a 5xx status code
func (o *ToProcessPostToProcessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this to process post to process o k response a status code equal to that given
func (o *ToProcessPostToProcessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the to process post to process o k response
func (o *ToProcessPostToProcessOK) Code() int {
	return 200
}

func (o *ToProcessPostToProcessOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/toProcess][%d] toProcessPostToProcessOK %s", 200, payload)
}

func (o *ToProcessPostToProcessOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/toProcess][%d] toProcessPostToProcessOK %s", 200, payload)
}

func (o *ToProcessPostToProcessOK) GetPayload() int32 {
	return o.Payload
}

func (o *ToProcessPostToProcessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
