// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// DocumentGetDocumentReader is a Reader for the DocumentGetDocument structure.
type DocumentGetDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DocumentGetDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDocumentGetDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/documents/{documentID}] Document_GetDocument", response, response.Code())
	}
}

// NewDocumentGetDocumentOK creates a DocumentGetDocumentOK with default headers values
func NewDocumentGetDocumentOK() *DocumentGetDocumentOK {
	return &DocumentGetDocumentOK{}
}

/*
DocumentGetDocumentOK describes a response with status code 200, with default header values.

Get a document
*/
type DocumentGetDocumentOK struct {
	Payload *model.DocumentAPIView
}

// IsSuccess returns true when this document get document o k response has a 2xx status code
func (o *DocumentGetDocumentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this document get document o k response has a 3xx status code
func (o *DocumentGetDocumentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this document get document o k response has a 4xx status code
func (o *DocumentGetDocumentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this document get document o k response has a 5xx status code
func (o *DocumentGetDocumentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this document get document o k response a status code equal to that given
func (o *DocumentGetDocumentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the document get document o k response
func (o *DocumentGetDocumentOK) Code() int {
	return 200
}

func (o *DocumentGetDocumentOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/documents/{documentID}][%d] documentGetDocumentOK %s", 200, payload)
}

func (o *DocumentGetDocumentOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/documents/{documentID}][%d] documentGetDocumentOK %s", 200, payload)
}

func (o *DocumentGetDocumentOK) GetPayload() *model.DocumentAPIView {
	return o.Payload
}

func (o *DocumentGetDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DocumentAPIView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
