// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewDocumentPostDocumentParams creates a new DocumentPostDocumentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDocumentPostDocumentParams() *DocumentPostDocumentParams {
	return &DocumentPostDocumentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDocumentPostDocumentParamsWithTimeout creates a new DocumentPostDocumentParams object
// with the ability to set a timeout on a request.
func NewDocumentPostDocumentParamsWithTimeout(timeout time.Duration) *DocumentPostDocumentParams {
	return &DocumentPostDocumentParams{
		timeout: timeout,
	}
}

// NewDocumentPostDocumentParamsWithContext creates a new DocumentPostDocumentParams object
// with the ability to set a context for a request.
func NewDocumentPostDocumentParamsWithContext(ctx context.Context) *DocumentPostDocumentParams {
	return &DocumentPostDocumentParams{
		Context: ctx,
	}
}

// NewDocumentPostDocumentParamsWithHTTPClient creates a new DocumentPostDocumentParams object
// with the ability to set a custom HTTPClient for a request.
func NewDocumentPostDocumentParamsWithHTTPClient(client *http.Client) *DocumentPostDocumentParams {
	return &DocumentPostDocumentParams{
		HTTPClient: client,
	}
}

/*
DocumentPostDocumentParams contains all the parameters to send to the API endpoint

	for the document post document operation.

	Typically these are written to a http.Request.
*/
type DocumentPostDocumentParams struct {

	// Document.
	Document *model.Document

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the document post document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentPostDocumentParams) WithDefaults() *DocumentPostDocumentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the document post document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DocumentPostDocumentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the document post document params
func (o *DocumentPostDocumentParams) WithTimeout(timeout time.Duration) *DocumentPostDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the document post document params
func (o *DocumentPostDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the document post document params
func (o *DocumentPostDocumentParams) WithContext(ctx context.Context) *DocumentPostDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the document post document params
func (o *DocumentPostDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the document post document params
func (o *DocumentPostDocumentParams) WithHTTPClient(client *http.Client) *DocumentPostDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the document post document params
func (o *DocumentPostDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDocument adds the document to the document post document params
func (o *DocumentPostDocumentParams) WithDocument(document *model.Document) *DocumentPostDocumentParams {
	o.SetDocument(document)
	return o
}

// SetDocument adds the document to the document post document params
func (o *DocumentPostDocumentParams) SetDocument(document *model.Document) {
	o.Document = document
}

// WriteToRequest writes these params to a swagger request
func (o *DocumentPostDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Document != nil {
		if err := r.SetBodyParam(o.Document); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
