// Code generated by go-swagger; DO NOT EDIT.

package daily_receipt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// DailyReceiptPostDailyReceiptBookEntryReader is a Reader for the DailyReceiptPostDailyReceiptBookEntry structure.
type DailyReceiptPostDailyReceiptBookEntryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DailyReceiptPostDailyReceiptBookEntryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDailyReceiptPostDailyReceiptBookEntryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/DailyReceiptBooks/commands/CreateEntryInOpenExistingOrNew] DailyReceipt_PostDailyReceiptBookEntry", response, response.Code())
	}
}

// NewDailyReceiptPostDailyReceiptBookEntryOK creates a DailyReceiptPostDailyReceiptBookEntryOK with default headers values
func NewDailyReceiptPostDailyReceiptBookEntryOK() *DailyReceiptPostDailyReceiptBookEntryOK {
	return &DailyReceiptPostDailyReceiptBookEntryOK{}
}

/*
DailyReceiptPostDailyReceiptBookEntryOK describes a response with status code 200, with default header values.

Save an daily receipt entry
*/
type DailyReceiptPostDailyReceiptBookEntryOK struct {
	Payload *model.PostDailyReceiptBookEntryResponseModel
}

// IsSuccess returns true when this daily receipt post daily receipt book entry o k response has a 2xx status code
func (o *DailyReceiptPostDailyReceiptBookEntryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this daily receipt post daily receipt book entry o k response has a 3xx status code
func (o *DailyReceiptPostDailyReceiptBookEntryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this daily receipt post daily receipt book entry o k response has a 4xx status code
func (o *DailyReceiptPostDailyReceiptBookEntryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this daily receipt post daily receipt book entry o k response has a 5xx status code
func (o *DailyReceiptPostDailyReceiptBookEntryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this daily receipt post daily receipt book entry o k response a status code equal to that given
func (o *DailyReceiptPostDailyReceiptBookEntryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the daily receipt post daily receipt book entry o k response
func (o *DailyReceiptPostDailyReceiptBookEntryOK) Code() int {
	return 200
}

func (o *DailyReceiptPostDailyReceiptBookEntryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/DailyReceiptBooks/commands/CreateEntryInOpenExistingOrNew][%d] dailyReceiptPostDailyReceiptBookEntryOK %s", 200, payload)
}

func (o *DailyReceiptPostDailyReceiptBookEntryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/DailyReceiptBooks/commands/CreateEntryInOpenExistingOrNew][%d] dailyReceiptPostDailyReceiptBookEntryOK %s", 200, payload)
}

func (o *DailyReceiptPostDailyReceiptBookEntryOK) GetPayload() *model.PostDailyReceiptBookEntryResponseModel {
	return o.Payload
}

func (o *DailyReceiptPostDailyReceiptBookEntryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.PostDailyReceiptBookEntryResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
