// Code generated by go-swagger; DO NOT EDIT.

package daily_receipt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDailyReceiptGetDailyReceiptBookParams creates a new DailyReceiptGetDailyReceiptBookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDailyReceiptGetDailyReceiptBookParams() *DailyReceiptGetDailyReceiptBookParams {
	return &DailyReceiptGetDailyReceiptBookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDailyReceiptGetDailyReceiptBookParamsWithTimeout creates a new DailyReceiptGetDailyReceiptBookParams object
// with the ability to set a timeout on a request.
func NewDailyReceiptGetDailyReceiptBookParamsWithTimeout(timeout time.Duration) *DailyReceiptGetDailyReceiptBookParams {
	return &DailyReceiptGetDailyReceiptBookParams{
		timeout: timeout,
	}
}

// NewDailyReceiptGetDailyReceiptBookParamsWithContext creates a new DailyReceiptGetDailyReceiptBookParams object
// with the ability to set a context for a request.
func NewDailyReceiptGetDailyReceiptBookParamsWithContext(ctx context.Context) *DailyReceiptGetDailyReceiptBookParams {
	return &DailyReceiptGetDailyReceiptBookParams{
		Context: ctx,
	}
}

// NewDailyReceiptGetDailyReceiptBookParamsWithHTTPClient creates a new DailyReceiptGetDailyReceiptBookParams object
// with the ability to set a custom HTTPClient for a request.
func NewDailyReceiptGetDailyReceiptBookParamsWithHTTPClient(client *http.Client) *DailyReceiptGetDailyReceiptBookParams {
	return &DailyReceiptGetDailyReceiptBookParams{
		HTTPClient: client,
	}
}

/*
DailyReceiptGetDailyReceiptBookParams contains all the parameters to send to the API endpoint

	for the daily receipt get daily receipt book operation.

	Typically these are written to a http.Request.
*/
type DailyReceiptGetDailyReceiptBookParams struct {

	// DailyReceiptBookID.
	//
	// Format: int32
	DailyReceiptBookID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the daily receipt get daily receipt book params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DailyReceiptGetDailyReceiptBookParams) WithDefaults() *DailyReceiptGetDailyReceiptBookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the daily receipt get daily receipt book params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DailyReceiptGetDailyReceiptBookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) WithTimeout(timeout time.Duration) *DailyReceiptGetDailyReceiptBookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) WithContext(ctx context.Context) *DailyReceiptGetDailyReceiptBookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) WithHTTPClient(client *http.Client) *DailyReceiptGetDailyReceiptBookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDailyReceiptBookID adds the dailyReceiptBookID to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) WithDailyReceiptBookID(dailyReceiptBookID int32) *DailyReceiptGetDailyReceiptBookParams {
	o.SetDailyReceiptBookID(dailyReceiptBookID)
	return o
}

// SetDailyReceiptBookID adds the dailyReceiptBookId to the daily receipt get daily receipt book params
func (o *DailyReceiptGetDailyReceiptBookParams) SetDailyReceiptBookID(dailyReceiptBookID int32) {
	o.DailyReceiptBookID = dailyReceiptBookID
}

// WriteToRequest writes these params to a swagger request
func (o *DailyReceiptGetDailyReceiptBookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param DailyReceiptBookID
	if err := r.SetPathParam("DailyReceiptBookID", swag.FormatInt32(o.DailyReceiptBookID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
