// Code generated by go-swagger; DO NOT EDIT.

package daily_receipt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewDailyReceiptPostDailyReceiptBookEntryParams creates a new DailyReceiptPostDailyReceiptBookEntryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDailyReceiptPostDailyReceiptBookEntryParams() *DailyReceiptPostDailyReceiptBookEntryParams {
	return &DailyReceiptPostDailyReceiptBookEntryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDailyReceiptPostDailyReceiptBookEntryParamsWithTimeout creates a new DailyReceiptPostDailyReceiptBookEntryParams object
// with the ability to set a timeout on a request.
func NewDailyReceiptPostDailyReceiptBookEntryParamsWithTimeout(timeout time.Duration) *DailyReceiptPostDailyReceiptBookEntryParams {
	return &DailyReceiptPostDailyReceiptBookEntryParams{
		timeout: timeout,
	}
}

// NewDailyReceiptPostDailyReceiptBookEntryParamsWithContext creates a new DailyReceiptPostDailyReceiptBookEntryParams object
// with the ability to set a context for a request.
func NewDailyReceiptPostDailyReceiptBookEntryParamsWithContext(ctx context.Context) *DailyReceiptPostDailyReceiptBookEntryParams {
	return &DailyReceiptPostDailyReceiptBookEntryParams{
		Context: ctx,
	}
}

// NewDailyReceiptPostDailyReceiptBookEntryParamsWithHTTPClient creates a new DailyReceiptPostDailyReceiptBookEntryParams object
// with the ability to set a custom HTTPClient for a request.
func NewDailyReceiptPostDailyReceiptBookEntryParamsWithHTTPClient(client *http.Client) *DailyReceiptPostDailyReceiptBookEntryParams {
	return &DailyReceiptPostDailyReceiptBookEntryParams{
		HTTPClient: client,
	}
}

/*
DailyReceiptPostDailyReceiptBookEntryParams contains all the parameters to send to the API endpoint

	for the daily receipt post daily receipt book entry operation.

	Typically these are written to a http.Request.
*/
type DailyReceiptPostDailyReceiptBookEntryParams struct {

	// DailyReceiptEntry.
	DailyReceiptEntry *model.DailyReceiptBookEntryModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the daily receipt post daily receipt book entry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DailyReceiptPostDailyReceiptBookEntryParams) WithDefaults() *DailyReceiptPostDailyReceiptBookEntryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the daily receipt post daily receipt book entry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DailyReceiptPostDailyReceiptBookEntryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) WithTimeout(timeout time.Duration) *DailyReceiptPostDailyReceiptBookEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) WithContext(ctx context.Context) *DailyReceiptPostDailyReceiptBookEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) WithHTTPClient(client *http.Client) *DailyReceiptPostDailyReceiptBookEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDailyReceiptEntry adds the dailyReceiptEntry to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) WithDailyReceiptEntry(dailyReceiptEntry *model.DailyReceiptBookEntryModel) *DailyReceiptPostDailyReceiptBookEntryParams {
	o.SetDailyReceiptEntry(dailyReceiptEntry)
	return o
}

// SetDailyReceiptEntry adds the dailyReceiptEntry to the daily receipt post daily receipt book entry params
func (o *DailyReceiptPostDailyReceiptBookEntryParams) SetDailyReceiptEntry(dailyReceiptEntry *model.DailyReceiptBookEntryModel) {
	o.DailyReceiptEntry = dailyReceiptEntry
}

// WriteToRequest writes these params to a swagger request
func (o *DailyReceiptPostDailyReceiptBookEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.DailyReceiptEntry != nil {
		if err := r.SetBodyParam(o.DailyReceiptEntry); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
