// Code generated by go-swagger; DO NOT EDIT.

package daily_receipt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// DailyReceiptGetDailyReceiptBookReader is a Reader for the DailyReceiptGetDailyReceiptBook structure.
type DailyReceiptGetDailyReceiptBookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DailyReceiptGetDailyReceiptBookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDailyReceiptGetDailyReceiptBookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/DailyReceiptBooks/{DailyReceiptBookID}] DailyReceipt_GetDailyReceiptBook", response, response.Code())
	}
}

// NewDailyReceiptGetDailyReceiptBookOK creates a DailyReceiptGetDailyReceiptBookOK with default headers values
func NewDailyReceiptGetDailyReceiptBookOK() *DailyReceiptGetDailyReceiptBookOK {
	return &DailyReceiptGetDailyReceiptBookOK{}
}

/*
DailyReceiptGetDailyReceiptBookOK describes a response with status code 200, with default header values.

Get an daily receipt book
*/
type DailyReceiptGetDailyReceiptBookOK struct {
	Payload *model.DailyReceiptBookModelResponseModel
}

// IsSuccess returns true when this daily receipt get daily receipt book o k response has a 2xx status code
func (o *DailyReceiptGetDailyReceiptBookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this daily receipt get daily receipt book o k response has a 3xx status code
func (o *DailyReceiptGetDailyReceiptBookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this daily receipt get daily receipt book o k response has a 4xx status code
func (o *DailyReceiptGetDailyReceiptBookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this daily receipt get daily receipt book o k response has a 5xx status code
func (o *DailyReceiptGetDailyReceiptBookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this daily receipt get daily receipt book o k response a status code equal to that given
func (o *DailyReceiptGetDailyReceiptBookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the daily receipt get daily receipt book o k response
func (o *DailyReceiptGetDailyReceiptBookOK) Code() int {
	return 200
}

func (o *DailyReceiptGetDailyReceiptBookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/DailyReceiptBooks/{DailyReceiptBookID}][%d] dailyReceiptGetDailyReceiptBookOK %s", 200, payload)
}

func (o *DailyReceiptGetDailyReceiptBookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/DailyReceiptBooks/{DailyReceiptBookID}][%d] dailyReceiptGetDailyReceiptBookOK %s", 200, payload)
}

func (o *DailyReceiptGetDailyReceiptBookOK) GetPayload() *model.DailyReceiptBookModelResponseModel {
	return o.Payload
}

func (o *DailyReceiptGetDailyReceiptBookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DailyReceiptBookModelResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
