// Code generated by go-swagger; DO NOT EDIT.

package peppol

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// PeppolGetParticipantInformationReader is a Reader for the PeppolGetParticipantInformation structure.
type PeppolGetParticipantInformationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeppolGetParticipantInformationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeppolGetParticipantInformationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/peppol/participantInformation/{VATorCBE}] Peppol_GetParticipantInformation", response, response.Code())
	}
}

// NewPeppolGetParticipantInformationOK creates a PeppolGetParticipantInformationOK with default headers values
func NewPeppolGetParticipantInformationOK() *PeppolGetParticipantInformationOK {
	return &PeppolGetParticipantInformationOK{}
}

/*
PeppolGetParticipantInformationOK describes a response with status code 200, with default header values.

Get Peppol participant information. API key is not required.
*/
type PeppolGetParticipantInformationOK struct {
	Payload *model.ParticipantInformationResponse
}

// IsSuccess returns true when this peppol get participant information o k response has a 2xx status code
func (o *PeppolGetParticipantInformationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peppol get participant information o k response has a 3xx status code
func (o *PeppolGetParticipantInformationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peppol get participant information o k response has a 4xx status code
func (o *PeppolGetParticipantInformationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peppol get participant information o k response has a 5xx status code
func (o *PeppolGetParticipantInformationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peppol get participant information o k response a status code equal to that given
func (o *PeppolGetParticipantInformationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peppol get participant information o k response
func (o *PeppolGetParticipantInformationOK) Code() int {
	return 200
}

func (o *PeppolGetParticipantInformationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/peppol/participantInformation/{VATorCBE}][%d] peppolGetParticipantInformationOK %s", 200, payload)
}

func (o *PeppolGetParticipantInformationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/peppol/participantInformation/{VATorCBE}][%d] peppolGetParticipantInformationOK %s", 200, payload)
}

func (o *PeppolGetParticipantInformationOK) GetPayload() *model.ParticipantInformationResponse {
	return o.Payload
}

func (o *PeppolGetParticipantInformationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ParticipantInformationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
