// Code generated by go-swagger; DO NOT EDIT.

package peppol

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new peppol API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new peppol API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new peppol API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for peppol API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ConsumesMediaTypes = []string{mime}
	}
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/json"}
}

// WithContentTypeApplicationxWwwFormUrlencoded sets the Content-Type header to "application/x-www-form-urlencoded".
func WithContentTypeApplicationxWwwFormUrlencoded(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/x-www-form-urlencoded"}
}

// WithContentTypeApplicationXML sets the Content-Type header to "application/xml".
func WithContentTypeApplicationXML(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/xml"}
}

// WithContentTypeTextJSON sets the Content-Type header to "text/json".
func WithContentTypeTextJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"text/json"}
}

// WithContentTypeTextXML sets the Content-Type header to "text/xml".
func WithContentTypeTextXML(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"text/xml"}
}

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptApplicationXML sets the Accept header to "application/xml".
func WithAcceptApplicationXML(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/xml"}
}

// WithAcceptTextJSON sets the Accept header to "text/json".
func WithAcceptTextJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/json"}
}

// WithAcceptTextXML sets the Accept header to "text/xml".
func WithAcceptTextXML(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/xml"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	PeppolDeleteParticipant(params *PeppolDeleteParticipantParams, opts ...ClientOption) (*PeppolDeleteParticipantOK, error)

	PeppolGetInbox(params *PeppolGetInboxParams, opts ...ClientOption) (*PeppolGetInboxOK, error)

	PeppolGetParticipantInformation(params *PeppolGetParticipantInformationParams, opts ...ClientOption) (*PeppolGetParticipantInformationOK, error)

	PeppolInboxItemConfirm(params *PeppolInboxItemConfirmParams, opts ...ClientOption) (*PeppolInboxItemConfirmOK, error)

	PeppolInboxItemRefuse(params *PeppolInboxItemRefuseParams, opts ...ClientOption) (*PeppolInboxItemRefuseOK, error)

	PeppolPostParticipant(params *PeppolPostParticipantParams, opts ...ClientOption) (*PeppolPostParticipantOK, error)

	PeppolPostSendOrder(params *PeppolPostSendOrderParams, opts ...ClientOption) (*PeppolPostSendOrderOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
PeppolDeleteParticipant peppol delete participant API
*/
func (a *Client) PeppolDeleteParticipant(params *PeppolDeleteParticipantParams, opts ...ClientOption) (*PeppolDeleteParticipantOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolDeleteParticipantParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_DeleteParticipant",
		Method:             "DELETE",
		PathPattern:        "/v1/peppol/participants",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolDeleteParticipantReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolDeleteParticipantOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_DeleteParticipant: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PeppolGetInbox peppol get inbox API
*/
func (a *Client) PeppolGetInbox(params *PeppolGetInboxParams, opts ...ClientOption) (*PeppolGetInboxOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolGetInboxParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_GetInbox",
		Method:             "GET",
		PathPattern:        "/v1/peppol/inbox",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolGetInboxReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolGetInboxOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_GetInbox: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PeppolGetParticipantInformation peppol get participant information API
*/
func (a *Client) PeppolGetParticipantInformation(params *PeppolGetParticipantInformationParams, opts ...ClientOption) (*PeppolGetParticipantInformationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolGetParticipantInformationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_GetParticipantInformation",
		Method:             "GET",
		PathPattern:        "/v1/peppol/participantInformation/{VATorCBE}",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolGetParticipantInformationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolGetParticipantInformationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_GetParticipantInformation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PeppolInboxItemConfirm peppol inbox item confirm API
*/
func (a *Client) PeppolInboxItemConfirm(params *PeppolInboxItemConfirmParams, opts ...ClientOption) (*PeppolInboxItemConfirmOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolInboxItemConfirmParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_InboxItemConfirm",
		Method:             "POST",
		PathPattern:        "/v1/peppol/inbox/{inboxItemId}/confirm",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolInboxItemConfirmReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolInboxItemConfirmOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_InboxItemConfirm: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PeppolInboxItemRefuse peppol inbox item refuse API
*/
func (a *Client) PeppolInboxItemRefuse(params *PeppolInboxItemRefuseParams, opts ...ClientOption) (*PeppolInboxItemRefuseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolInboxItemRefuseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_InboxItemRefuse",
		Method:             "POST",
		PathPattern:        "/v1/peppol/inbox/{inboxItemId}/refuse",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolInboxItemRefuseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolInboxItemRefuseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_InboxItemRefuse: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PeppolPostParticipant peppol post participant API
*/
func (a *Client) PeppolPostParticipant(params *PeppolPostParticipantParams, opts ...ClientOption) (*PeppolPostParticipantOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolPostParticipantParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_PostParticipant",
		Method:             "POST",
		PathPattern:        "/v1/peppol/participants",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolPostParticipantReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolPostParticipantOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_PostParticipant: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PeppolPostSendOrder peppol post send order API
*/
func (a *Client) PeppolPostSendOrder(params *PeppolPostSendOrderParams, opts ...ClientOption) (*PeppolPostSendOrderOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPeppolPostSendOrderParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Peppol_PostSendOrder",
		Method:             "POST",
		PathPattern:        "/v1/peppol/sendOrder",
		ProducesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PeppolPostSendOrderReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PeppolPostSendOrderOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Peppol_PostSendOrder: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
