// Code generated by go-swagger; DO NOT EDIT.

package peppol

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PeppolPostSendOrderReader is a Reader for the PeppolPostSendOrder structure.
type PeppolPostSendOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeppolPostSendOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeppolPostSendOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/peppol/sendOrder] Peppol_PostSendOrder", response, response.Code())
	}
}

// NewPeppolPostSendOrderOK creates a PeppolPostSendOrderOK with default headers values
func NewPeppolPostSendOrderOK() *PeppolPostSendOrderOK {
	return &PeppolPostSendOrderOK{}
}

/*
PeppolPostSendOrderOK describes a response with status code 200, with default header values.

Send a direct Peppol message. Compatible with receivers that support Invoice5, Creditnote5, BisV3 Invoice or BisV3 Creditnote
*/
type PeppolPostSendOrderOK struct {
	Payload int32
}

// IsSuccess returns true when this peppol post send order o k response has a 2xx status code
func (o *PeppolPostSendOrderOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this peppol post send order o k response has a 3xx status code
func (o *PeppolPostSendOrderOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this peppol post send order o k response has a 4xx status code
func (o *PeppolPostSendOrderOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this peppol post send order o k response has a 5xx status code
func (o *PeppolPostSendOrderOK) IsServerError() bool {
	return false
}

// IsCode returns true when this peppol post send order o k response a status code equal to that given
func (o *PeppolPostSendOrderOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the peppol post send order o k response
func (o *PeppolPostSendOrderOK) Code() int {
	return 200
}

func (o *PeppolPostSendOrderOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/peppol/sendOrder][%d] peppolPostSendOrderOK %s", 200, payload)
}

func (o *PeppolPostSendOrderOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/peppol/sendOrder][%d] peppolPostSendOrderOK %s", 200, payload)
}

func (o *PeppolPostSendOrderOK) GetPayload() int32 {
	return o.Payload
}

func (o *PeppolPostSendOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
