// Code generated by go-swagger; DO NOT EDIT.

package peppol

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPeppolInboxItemConfirmParams creates a new PeppolInboxItemConfirmParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPeppolInboxItemConfirmParams() *PeppolInboxItemConfirmParams {
	return &PeppolInboxItemConfirmParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPeppolInboxItemConfirmParamsWithTimeout creates a new PeppolInboxItemConfirmParams object
// with the ability to set a timeout on a request.
func NewPeppolInboxItemConfirmParamsWithTimeout(timeout time.Duration) *PeppolInboxItemConfirmParams {
	return &PeppolInboxItemConfirmParams{
		timeout: timeout,
	}
}

// NewPeppolInboxItemConfirmParamsWithContext creates a new PeppolInboxItemConfirmParams object
// with the ability to set a context for a request.
func NewPeppolInboxItemConfirmParamsWithContext(ctx context.Context) *PeppolInboxItemConfirmParams {
	return &PeppolInboxItemConfirmParams{
		Context: ctx,
	}
}

// NewPeppolInboxItemConfirmParamsWithHTTPClient creates a new PeppolInboxItemConfirmParams object
// with the ability to set a custom HTTPClient for a request.
func NewPeppolInboxItemConfirmParamsWithHTTPClient(client *http.Client) *PeppolInboxItemConfirmParams {
	return &PeppolInboxItemConfirmParams{
		HTTPClient: client,
	}
}

/*
PeppolInboxItemConfirmParams contains all the parameters to send to the API endpoint

	for the peppol inbox item confirm operation.

	Typically these are written to a http.Request.
*/
type PeppolInboxItemConfirmParams struct {

	// InboxItemID.
	//
	// Format: int32
	InboxItemID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the peppol inbox item confirm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeppolInboxItemConfirmParams) WithDefaults() *PeppolInboxItemConfirmParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the peppol inbox item confirm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PeppolInboxItemConfirmParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) WithTimeout(timeout time.Duration) *PeppolInboxItemConfirmParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) WithContext(ctx context.Context) *PeppolInboxItemConfirmParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) WithHTTPClient(client *http.Client) *PeppolInboxItemConfirmParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInboxItemID adds the inboxItemID to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) WithInboxItemID(inboxItemID int32) *PeppolInboxItemConfirmParams {
	o.SetInboxItemID(inboxItemID)
	return o
}

// SetInboxItemID adds the inboxItemId to the peppol inbox item confirm params
func (o *PeppolInboxItemConfirmParams) SetInboxItemID(inboxItemID int32) {
	o.InboxItemID = inboxItemID
}

// WriteToRequest writes these params to a swagger request
func (o *PeppolInboxItemConfirmParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inboxItemId
	if err := r.SetPathParam("inboxItemId", swag.FormatInt32(o.InboxItemID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
