// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEinvoiceDeleteRegistrationParams creates a new EinvoiceDeleteRegistrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoiceDeleteRegistrationParams() *EinvoiceDeleteRegistrationParams {
	return &EinvoiceDeleteRegistrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoiceDeleteRegistrationParamsWithTimeout creates a new EinvoiceDeleteRegistrationParams object
// with the ability to set a timeout on a request.
func NewEinvoiceDeleteRegistrationParamsWithTimeout(timeout time.Duration) *EinvoiceDeleteRegistrationParams {
	return &EinvoiceDeleteRegistrationParams{
		timeout: timeout,
	}
}

// NewEinvoiceDeleteRegistrationParamsWithContext creates a new EinvoiceDeleteRegistrationParams object
// with the ability to set a context for a request.
func NewEinvoiceDeleteRegistrationParamsWithContext(ctx context.Context) *EinvoiceDeleteRegistrationParams {
	return &EinvoiceDeleteRegistrationParams{
		Context: ctx,
	}
}

// NewEinvoiceDeleteRegistrationParamsWithHTTPClient creates a new EinvoiceDeleteRegistrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoiceDeleteRegistrationParamsWithHTTPClient(client *http.Client) *EinvoiceDeleteRegistrationParams {
	return &EinvoiceDeleteRegistrationParams{
		HTTPClient: client,
	}
}

/*
EinvoiceDeleteRegistrationParams contains all the parameters to send to the API endpoint

	for the einvoice delete registration operation.

	Typically these are written to a http.Request.
*/
type EinvoiceDeleteRegistrationParams struct {

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice delete registration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceDeleteRegistrationParams) WithDefaults() *EinvoiceDeleteRegistrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice delete registration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceDeleteRegistrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) WithTimeout(timeout time.Duration) *EinvoiceDeleteRegistrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) WithContext(ctx context.Context) *EinvoiceDeleteRegistrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) WithHTTPClient(client *http.Client) *EinvoiceDeleteRegistrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegistrationID adds the registrationID to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) WithRegistrationID(registrationID int32) *EinvoiceDeleteRegistrationParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice delete registration params
func (o *EinvoiceDeleteRegistrationParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoiceDeleteRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
