// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEinvoiceGetRegistrationParams creates a new EinvoiceGetRegistrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoiceGetRegistrationParams() *EinvoiceGetRegistrationParams {
	return &EinvoiceGetRegistrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoiceGetRegistrationParamsWithTimeout creates a new EinvoiceGetRegistrationParams object
// with the ability to set a timeout on a request.
func NewEinvoiceGetRegistrationParamsWithTimeout(timeout time.Duration) *EinvoiceGetRegistrationParams {
	return &EinvoiceGetRegistrationParams{
		timeout: timeout,
	}
}

// NewEinvoiceGetRegistrationParamsWithContext creates a new EinvoiceGetRegistrationParams object
// with the ability to set a context for a request.
func NewEinvoiceGetRegistrationParamsWithContext(ctx context.Context) *EinvoiceGetRegistrationParams {
	return &EinvoiceGetRegistrationParams{
		Context: ctx,
	}
}

// NewEinvoiceGetRegistrationParamsWithHTTPClient creates a new EinvoiceGetRegistrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoiceGetRegistrationParamsWithHTTPClient(client *http.Client) *EinvoiceGetRegistrationParams {
	return &EinvoiceGetRegistrationParams{
		HTTPClient: client,
	}
}

/*
EinvoiceGetRegistrationParams contains all the parameters to send to the API endpoint

	for the einvoice get registration operation.

	Typically these are written to a http.Request.
*/
type EinvoiceGetRegistrationParams struct {

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice get registration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetRegistrationParams) WithDefaults() *EinvoiceGetRegistrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice get registration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetRegistrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) WithTimeout(timeout time.Duration) *EinvoiceGetRegistrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) WithContext(ctx context.Context) *EinvoiceGetRegistrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) WithHTTPClient(client *http.Client) *EinvoiceGetRegistrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegistrationID adds the registrationID to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) WithRegistrationID(registrationID int32) *EinvoiceGetRegistrationParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice get registration params
func (o *EinvoiceGetRegistrationParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoiceGetRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
