// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEinvoiceGetOrderParams creates a new EinvoiceGetOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoiceGetOrderParams() *EinvoiceGetOrderParams {
	return &EinvoiceGetOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoiceGetOrderParamsWithTimeout creates a new EinvoiceGetOrderParams object
// with the ability to set a timeout on a request.
func NewEinvoiceGetOrderParamsWithTimeout(timeout time.Duration) *EinvoiceGetOrderParams {
	return &EinvoiceGetOrderParams{
		timeout: timeout,
	}
}

// NewEinvoiceGetOrderParamsWithContext creates a new EinvoiceGetOrderParams object
// with the ability to set a context for a request.
func NewEinvoiceGetOrderParamsWithContext(ctx context.Context) *EinvoiceGetOrderParams {
	return &EinvoiceGetOrderParams{
		Context: ctx,
	}
}

// NewEinvoiceGetOrderParamsWithHTTPClient creates a new EinvoiceGetOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoiceGetOrderParamsWithHTTPClient(client *http.Client) *EinvoiceGetOrderParams {
	return &EinvoiceGetOrderParams{
		HTTPClient: client,
	}
}

/*
EinvoiceGetOrderParams contains all the parameters to send to the API endpoint

	for the einvoice get order operation.

	Typically these are written to a http.Request.
*/
type EinvoiceGetOrderParams struct {

	// OrderID.
	//
	// Format: int32
	OrderID int32

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice get order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetOrderParams) WithDefaults() *EinvoiceGetOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice get order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice get order params
func (o *EinvoiceGetOrderParams) WithTimeout(timeout time.Duration) *EinvoiceGetOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice get order params
func (o *EinvoiceGetOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice get order params
func (o *EinvoiceGetOrderParams) WithContext(ctx context.Context) *EinvoiceGetOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice get order params
func (o *EinvoiceGetOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice get order params
func (o *EinvoiceGetOrderParams) WithHTTPClient(client *http.Client) *EinvoiceGetOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice get order params
func (o *EinvoiceGetOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the einvoice get order params
func (o *EinvoiceGetOrderParams) WithOrderID(orderID int32) *EinvoiceGetOrderParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the einvoice get order params
func (o *EinvoiceGetOrderParams) SetOrderID(orderID int32) {
	o.OrderID = orderID
}

// WithRegistrationID adds the registrationID to the einvoice get order params
func (o *EinvoiceGetOrderParams) WithRegistrationID(registrationID int32) *EinvoiceGetOrderParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice get order params
func (o *EinvoiceGetOrderParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoiceGetOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orderID
	if err := r.SetPathParam("orderID", swag.FormatInt32(o.OrderID)); err != nil {
		return err
	}

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
