// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EinvoiceGetFileReader is a Reader for the EinvoiceGetFile structure.
type EinvoiceGetFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EinvoiceGetFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEinvoiceGetFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/einvoices/registrations/{registrationID}/files/{fileID}] Einvoice_GetFile", response, response.Code())
	}
}

// NewEinvoiceGetFileOK creates a EinvoiceGetFileOK with default headers values
func NewEinvoiceGetFileOK() *EinvoiceGetFileOK {
	return &EinvoiceGetFileOK{}
}

/*
EinvoiceGetFileOK describes a response with status code 200, with default header values.

Get a file
*/
type EinvoiceGetFileOK struct {
	Payload int32
}

// IsSuccess returns true when this einvoice get file o k response has a 2xx status code
func (o *EinvoiceGetFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this einvoice get file o k response has a 3xx status code
func (o *EinvoiceGetFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this einvoice get file o k response has a 4xx status code
func (o *EinvoiceGetFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this einvoice get file o k response has a 5xx status code
func (o *EinvoiceGetFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this einvoice get file o k response a status code equal to that given
func (o *EinvoiceGetFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the einvoice get file o k response
func (o *EinvoiceGetFileOK) Code() int {
	return 200
}

func (o *EinvoiceGetFileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/einvoices/registrations/{registrationID}/files/{fileID}][%d] einvoiceGetFileOK %s", 200, payload)
}

func (o *EinvoiceGetFileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/einvoices/registrations/{registrationID}/files/{fileID}][%d] einvoiceGetFileOK %s", 200, payload)
}

func (o *EinvoiceGetFileOK) GetPayload() int32 {
	return o.Payload
}

func (o *EinvoiceGetFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
