// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/becoded/billit/model"
)

// NewEinvoicePostSendParams creates a new EinvoicePostSendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoicePostSendParams() *EinvoicePostSendParams {
	return &EinvoicePostSendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoicePostSendParamsWithTimeout creates a new EinvoicePostSendParams object
// with the ability to set a timeout on a request.
func NewEinvoicePostSendParamsWithTimeout(timeout time.Duration) *EinvoicePostSendParams {
	return &EinvoicePostSendParams{
		timeout: timeout,
	}
}

// NewEinvoicePostSendParamsWithContext creates a new EinvoicePostSendParams object
// with the ability to set a context for a request.
func NewEinvoicePostSendParamsWithContext(ctx context.Context) *EinvoicePostSendParams {
	return &EinvoicePostSendParams{
		Context: ctx,
	}
}

// NewEinvoicePostSendParamsWithHTTPClient creates a new EinvoicePostSendParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoicePostSendParamsWithHTTPClient(client *http.Client) *EinvoicePostSendParams {
	return &EinvoicePostSendParams{
		HTTPClient: client,
	}
}

/*
EinvoicePostSendParams contains all the parameters to send to the API endpoint

	for the einvoice post send operation.

	Typically these are written to a http.Request.
*/
type EinvoicePostSendParams struct {

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	// SendRequest.
	SendRequest *model.CreateAndSendEDocumentPost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice post send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoicePostSendParams) WithDefaults() *EinvoicePostSendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice post send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoicePostSendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice post send params
func (o *EinvoicePostSendParams) WithTimeout(timeout time.Duration) *EinvoicePostSendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice post send params
func (o *EinvoicePostSendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice post send params
func (o *EinvoicePostSendParams) WithContext(ctx context.Context) *EinvoicePostSendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice post send params
func (o *EinvoicePostSendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice post send params
func (o *EinvoicePostSendParams) WithHTTPClient(client *http.Client) *EinvoicePostSendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice post send params
func (o *EinvoicePostSendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegistrationID adds the registrationID to the einvoice post send params
func (o *EinvoicePostSendParams) WithRegistrationID(registrationID int32) *EinvoicePostSendParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice post send params
func (o *EinvoicePostSendParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WithSendRequest adds the sendRequest to the einvoice post send params
func (o *EinvoicePostSendParams) WithSendRequest(sendRequest *model.CreateAndSendEDocumentPost) *EinvoicePostSendParams {
	o.SetSendRequest(sendRequest)
	return o
}

// SetSendRequest adds the sendRequest to the einvoice post send params
func (o *EinvoicePostSendParams) SetSendRequest(sendRequest *model.CreateAndSendEDocumentPost) {
	o.SendRequest = sendRequest
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoicePostSendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}
	if o.SendRequest != nil {
		if err := r.SetBodyParam(o.SendRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
