// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// EinvoicePostWebhookReader is a Reader for the EinvoicePostWebhook structure.
type EinvoicePostWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EinvoicePostWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEinvoicePostWebhookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/einvoices/registrations/{registrationID}/webhooks] Einvoice_PostWebhook", response, response.Code())
	}
}

// NewEinvoicePostWebhookOK creates a EinvoicePostWebhookOK with default headers values
func NewEinvoicePostWebhookOK() *EinvoicePostWebhookOK {
	return &EinvoicePostWebhookOK{}
}

/*
EinvoicePostWebhookOK describes a response with status code 200, with default header values.

Save an webhook
*/
type EinvoicePostWebhookOK struct {
	Payload *model.Webhook
}

// IsSuccess returns true when this einvoice post webhook o k response has a 2xx status code
func (o *EinvoicePostWebhookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this einvoice post webhook o k response has a 3xx status code
func (o *EinvoicePostWebhookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this einvoice post webhook o k response has a 4xx status code
func (o *EinvoicePostWebhookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this einvoice post webhook o k response has a 5xx status code
func (o *EinvoicePostWebhookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this einvoice post webhook o k response a status code equal to that given
func (o *EinvoicePostWebhookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the einvoice post webhook o k response
func (o *EinvoicePostWebhookOK) Code() int {
	return 200
}

func (o *EinvoicePostWebhookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/einvoices/registrations/{registrationID}/webhooks][%d] einvoicePostWebhookOK %s", 200, payload)
}

func (o *EinvoicePostWebhookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/einvoices/registrations/{registrationID}/webhooks][%d] einvoicePostWebhookOK %s", 200, payload)
}

func (o *EinvoicePostWebhookOK) GetPayload() *model.Webhook {
	return o.Payload
}

func (o *EinvoicePostWebhookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Webhook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
