// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/becoded/billit/model"
)

// NewEinvoicePostWebhookParams creates a new EinvoicePostWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoicePostWebhookParams() *EinvoicePostWebhookParams {
	return &EinvoicePostWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoicePostWebhookParamsWithTimeout creates a new EinvoicePostWebhookParams object
// with the ability to set a timeout on a request.
func NewEinvoicePostWebhookParamsWithTimeout(timeout time.Duration) *EinvoicePostWebhookParams {
	return &EinvoicePostWebhookParams{
		timeout: timeout,
	}
}

// NewEinvoicePostWebhookParamsWithContext creates a new EinvoicePostWebhookParams object
// with the ability to set a context for a request.
func NewEinvoicePostWebhookParamsWithContext(ctx context.Context) *EinvoicePostWebhookParams {
	return &EinvoicePostWebhookParams{
		Context: ctx,
	}
}

// NewEinvoicePostWebhookParamsWithHTTPClient creates a new EinvoicePostWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoicePostWebhookParamsWithHTTPClient(client *http.Client) *EinvoicePostWebhookParams {
	return &EinvoicePostWebhookParams{
		HTTPClient: client,
	}
}

/*
EinvoicePostWebhookParams contains all the parameters to send to the API endpoint

	for the einvoice post webhook operation.

	Typically these are written to a http.Request.
*/
type EinvoicePostWebhookParams struct {

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	// Webhook.
	Webhook *model.Webhook

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice post webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoicePostWebhookParams) WithDefaults() *EinvoicePostWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice post webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoicePostWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) WithTimeout(timeout time.Duration) *EinvoicePostWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) WithContext(ctx context.Context) *EinvoicePostWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) WithHTTPClient(client *http.Client) *EinvoicePostWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegistrationID adds the registrationID to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) WithRegistrationID(registrationID int32) *EinvoicePostWebhookParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WithWebhook adds the webhook to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) WithWebhook(webhook *model.Webhook) *EinvoicePostWebhookParams {
	o.SetWebhook(webhook)
	return o
}

// SetWebhook adds the webhook to the einvoice post webhook params
func (o *EinvoicePostWebhookParams) SetWebhook(webhook *model.Webhook) {
	o.Webhook = webhook
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoicePostWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}
	if o.Webhook != nil {
		if err := r.SetBodyParam(o.Webhook); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
