// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEinvoicePatchEntityParams creates a new EinvoicePatchEntityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoicePatchEntityParams() *EinvoicePatchEntityParams {
	return &EinvoicePatchEntityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoicePatchEntityParamsWithTimeout creates a new EinvoicePatchEntityParams object
// with the ability to set a timeout on a request.
func NewEinvoicePatchEntityParamsWithTimeout(timeout time.Duration) *EinvoicePatchEntityParams {
	return &EinvoicePatchEntityParams{
		timeout: timeout,
	}
}

// NewEinvoicePatchEntityParamsWithContext creates a new EinvoicePatchEntityParams object
// with the ability to set a context for a request.
func NewEinvoicePatchEntityParamsWithContext(ctx context.Context) *EinvoicePatchEntityParams {
	return &EinvoicePatchEntityParams{
		Context: ctx,
	}
}

// NewEinvoicePatchEntityParamsWithHTTPClient creates a new EinvoicePatchEntityParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoicePatchEntityParamsWithHTTPClient(client *http.Client) *EinvoicePatchEntityParams {
	return &EinvoicePatchEntityParams{
		HTTPClient: client,
	}
}

/*
EinvoicePatchEntityParams contains all the parameters to send to the API endpoint

	for the einvoice patch entity operation.

	Typically these are written to a http.Request.
*/
type EinvoicePatchEntityParams struct {

	// EinvoiceRegistrationPatch.
	EinvoiceRegistrationPatch interface{}

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice patch entity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoicePatchEntityParams) WithDefaults() *EinvoicePatchEntityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice patch entity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoicePatchEntityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) WithTimeout(timeout time.Duration) *EinvoicePatchEntityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) WithContext(ctx context.Context) *EinvoicePatchEntityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) WithHTTPClient(client *http.Client) *EinvoicePatchEntityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEinvoiceRegistrationPatch adds the einvoiceRegistrationPatch to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) WithEinvoiceRegistrationPatch(einvoiceRegistrationPatch interface{}) *EinvoicePatchEntityParams {
	o.SetEinvoiceRegistrationPatch(einvoiceRegistrationPatch)
	return o
}

// SetEinvoiceRegistrationPatch adds the einvoiceRegistrationPatch to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) SetEinvoiceRegistrationPatch(einvoiceRegistrationPatch interface{}) {
	o.EinvoiceRegistrationPatch = einvoiceRegistrationPatch
}

// WithRegistrationID adds the registrationID to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) WithRegistrationID(registrationID int32) *EinvoicePatchEntityParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice patch entity params
func (o *EinvoicePatchEntityParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoicePatchEntityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.EinvoiceRegistrationPatch != nil {
		if err := r.SetBodyParam(o.EinvoiceRegistrationPatch); err != nil {
			return err
		}
	}

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
