// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// EinvoicePatchEntityReader is a Reader for the EinvoicePatchEntity structure.
type EinvoicePatchEntityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EinvoicePatchEntityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEinvoicePatchEntityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/einvoices/registrations/{registrationID}] Einvoice_PatchEntity", response, response.Code())
	}
}

// NewEinvoicePatchEntityOK creates a EinvoicePatchEntityOK with default headers values
func NewEinvoicePatchEntityOK() *EinvoicePatchEntityOK {
	return &EinvoicePatchEntityOK{}
}

/*
EinvoicePatchEntityOK describes a response with status code 200, with default header values.

Update a entity
*/
type EinvoicePatchEntityOK struct {
	Payload *model.AccountRegistrationResponse
}

// IsSuccess returns true when this einvoice patch entity o k response has a 2xx status code
func (o *EinvoicePatchEntityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this einvoice patch entity o k response has a 3xx status code
func (o *EinvoicePatchEntityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this einvoice patch entity o k response has a 4xx status code
func (o *EinvoicePatchEntityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this einvoice patch entity o k response has a 5xx status code
func (o *EinvoicePatchEntityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this einvoice patch entity o k response a status code equal to that given
func (o *EinvoicePatchEntityOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the einvoice patch entity o k response
func (o *EinvoicePatchEntityOK) Code() int {
	return 200
}

func (o *EinvoicePatchEntityOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/einvoices/registrations/{registrationID}][%d] einvoicePatchEntityOK %s", 200, payload)
}

func (o *EinvoicePatchEntityOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/einvoices/registrations/{registrationID}][%d] einvoicePatchEntityOK %s", 200, payload)
}

func (o *EinvoicePatchEntityOK) GetPayload() *model.AccountRegistrationResponse {
	return o.Payload
}

func (o *EinvoicePatchEntityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.AccountRegistrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
