// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EinvoiceDeleteRegistrationIntegrationReader is a Reader for the EinvoiceDeleteRegistrationIntegration structure.
type EinvoiceDeleteRegistrationIntegrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EinvoiceDeleteRegistrationIntegrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEinvoiceDeleteRegistrationIntegrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/einvoices/registrations/{registrationID}/integrations/{integrationID}] Einvoice_DeleteRegistrationIntegration", response, response.Code())
	}
}

// NewEinvoiceDeleteRegistrationIntegrationOK creates a EinvoiceDeleteRegistrationIntegrationOK with default headers values
func NewEinvoiceDeleteRegistrationIntegrationOK() *EinvoiceDeleteRegistrationIntegrationOK {
	return &EinvoiceDeleteRegistrationIntegrationOK{}
}

/*
EinvoiceDeleteRegistrationIntegrationOK describes a response with status code 200, with default header values.

Deactivate an integration
*/
type EinvoiceDeleteRegistrationIntegrationOK struct {
	Payload int32
}

// IsSuccess returns true when this einvoice delete registration integration o k response has a 2xx status code
func (o *EinvoiceDeleteRegistrationIntegrationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this einvoice delete registration integration o k response has a 3xx status code
func (o *EinvoiceDeleteRegistrationIntegrationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this einvoice delete registration integration o k response has a 4xx status code
func (o *EinvoiceDeleteRegistrationIntegrationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this einvoice delete registration integration o k response has a 5xx status code
func (o *EinvoiceDeleteRegistrationIntegrationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this einvoice delete registration integration o k response a status code equal to that given
func (o *EinvoiceDeleteRegistrationIntegrationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the einvoice delete registration integration o k response
func (o *EinvoiceDeleteRegistrationIntegrationOK) Code() int {
	return 200
}

func (o *EinvoiceDeleteRegistrationIntegrationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/einvoices/registrations/{registrationID}/integrations/{integrationID}][%d] einvoiceDeleteRegistrationIntegrationOK %s", 200, payload)
}

func (o *EinvoiceDeleteRegistrationIntegrationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/einvoices/registrations/{registrationID}/integrations/{integrationID}][%d] einvoiceDeleteRegistrationIntegrationOK %s", 200, payload)
}

func (o *EinvoiceDeleteRegistrationIntegrationOK) GetPayload() int32 {
	return o.Payload
}

func (o *EinvoiceDeleteRegistrationIntegrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
