// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEinvoiceGetFileParams creates a new EinvoiceGetFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoiceGetFileParams() *EinvoiceGetFileParams {
	return &EinvoiceGetFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoiceGetFileParamsWithTimeout creates a new EinvoiceGetFileParams object
// with the ability to set a timeout on a request.
func NewEinvoiceGetFileParamsWithTimeout(timeout time.Duration) *EinvoiceGetFileParams {
	return &EinvoiceGetFileParams{
		timeout: timeout,
	}
}

// NewEinvoiceGetFileParamsWithContext creates a new EinvoiceGetFileParams object
// with the ability to set a context for a request.
func NewEinvoiceGetFileParamsWithContext(ctx context.Context) *EinvoiceGetFileParams {
	return &EinvoiceGetFileParams{
		Context: ctx,
	}
}

// NewEinvoiceGetFileParamsWithHTTPClient creates a new EinvoiceGetFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoiceGetFileParamsWithHTTPClient(client *http.Client) *EinvoiceGetFileParams {
	return &EinvoiceGetFileParams{
		HTTPClient: client,
	}
}

/*
EinvoiceGetFileParams contains all the parameters to send to the API endpoint

	for the einvoice get file operation.

	Typically these are written to a http.Request.
*/
type EinvoiceGetFileParams struct {

	// FileID.
	//
	// Format: uuid
	FileID strfmt.UUID

	// RegistrationID.
	//
	// Format: int32
	RegistrationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice get file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetFileParams) WithDefaults() *EinvoiceGetFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice get file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice get file params
func (o *EinvoiceGetFileParams) WithTimeout(timeout time.Duration) *EinvoiceGetFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice get file params
func (o *EinvoiceGetFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice get file params
func (o *EinvoiceGetFileParams) WithContext(ctx context.Context) *EinvoiceGetFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice get file params
func (o *EinvoiceGetFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice get file params
func (o *EinvoiceGetFileParams) WithHTTPClient(client *http.Client) *EinvoiceGetFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice get file params
func (o *EinvoiceGetFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileID adds the fileID to the einvoice get file params
func (o *EinvoiceGetFileParams) WithFileID(fileID strfmt.UUID) *EinvoiceGetFileParams {
	o.SetFileID(fileID)
	return o
}

// SetFileID adds the fileId to the einvoice get file params
func (o *EinvoiceGetFileParams) SetFileID(fileID strfmt.UUID) {
	o.FileID = fileID
}

// WithRegistrationID adds the registrationID to the einvoice get file params
func (o *EinvoiceGetFileParams) WithRegistrationID(registrationID int32) *EinvoiceGetFileParams {
	o.SetRegistrationID(registrationID)
	return o
}

// SetRegistrationID adds the registrationId to the einvoice get file params
func (o *EinvoiceGetFileParams) SetRegistrationID(registrationID int32) {
	o.RegistrationID = registrationID
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoiceGetFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fileID
	if err := r.SetPathParam("fileID", o.FileID.String()); err != nil {
		return err
	}

	// path param registrationID
	if err := r.SetPathParam("registrationID", swag.FormatInt32(o.RegistrationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
