// Code generated by go-swagger; DO NOT EDIT.

package einvoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEinvoiceGetRegistrationsParams creates a new EinvoiceGetRegistrationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEinvoiceGetRegistrationsParams() *EinvoiceGetRegistrationsParams {
	return &EinvoiceGetRegistrationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEinvoiceGetRegistrationsParamsWithTimeout creates a new EinvoiceGetRegistrationsParams object
// with the ability to set a timeout on a request.
func NewEinvoiceGetRegistrationsParamsWithTimeout(timeout time.Duration) *EinvoiceGetRegistrationsParams {
	return &EinvoiceGetRegistrationsParams{
		timeout: timeout,
	}
}

// NewEinvoiceGetRegistrationsParamsWithContext creates a new EinvoiceGetRegistrationsParams object
// with the ability to set a context for a request.
func NewEinvoiceGetRegistrationsParamsWithContext(ctx context.Context) *EinvoiceGetRegistrationsParams {
	return &EinvoiceGetRegistrationsParams{
		Context: ctx,
	}
}

// NewEinvoiceGetRegistrationsParamsWithHTTPClient creates a new EinvoiceGetRegistrationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewEinvoiceGetRegistrationsParamsWithHTTPClient(client *http.Client) *EinvoiceGetRegistrationsParams {
	return &EinvoiceGetRegistrationsParams{
		HTTPClient: client,
	}
}

/*
EinvoiceGetRegistrationsParams contains all the parameters to send to the API endpoint

	for the einvoice get registrations operation.

	Typically these are written to a http.Request.
*/
type EinvoiceGetRegistrationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the einvoice get registrations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetRegistrationsParams) WithDefaults() *EinvoiceGetRegistrationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the einvoice get registrations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EinvoiceGetRegistrationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the einvoice get registrations params
func (o *EinvoiceGetRegistrationsParams) WithTimeout(timeout time.Duration) *EinvoiceGetRegistrationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the einvoice get registrations params
func (o *EinvoiceGetRegistrationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the einvoice get registrations params
func (o *EinvoiceGetRegistrationsParams) WithContext(ctx context.Context) *EinvoiceGetRegistrationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the einvoice get registrations params
func (o *EinvoiceGetRegistrationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the einvoice get registrations params
func (o *EinvoiceGetRegistrationsParams) WithHTTPClient(client *http.Client) *EinvoiceGetRegistrationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the einvoice get registrations params
func (o *EinvoiceGetRegistrationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EinvoiceGetRegistrationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
