// Code generated by go-swagger; DO NOT EDIT.

package cashbook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCashbookGetCashbookHistoryParams creates a new CashbookGetCashbookHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCashbookGetCashbookHistoryParams() *CashbookGetCashbookHistoryParams {
	return &CashbookGetCashbookHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCashbookGetCashbookHistoryParamsWithTimeout creates a new CashbookGetCashbookHistoryParams object
// with the ability to set a timeout on a request.
func NewCashbookGetCashbookHistoryParamsWithTimeout(timeout time.Duration) *CashbookGetCashbookHistoryParams {
	return &CashbookGetCashbookHistoryParams{
		timeout: timeout,
	}
}

// NewCashbookGetCashbookHistoryParamsWithContext creates a new CashbookGetCashbookHistoryParams object
// with the ability to set a context for a request.
func NewCashbookGetCashbookHistoryParamsWithContext(ctx context.Context) *CashbookGetCashbookHistoryParams {
	return &CashbookGetCashbookHistoryParams{
		Context: ctx,
	}
}

// NewCashbookGetCashbookHistoryParamsWithHTTPClient creates a new CashbookGetCashbookHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCashbookGetCashbookHistoryParamsWithHTTPClient(client *http.Client) *CashbookGetCashbookHistoryParams {
	return &CashbookGetCashbookHistoryParams{
		HTTPClient: client,
	}
}

/*
CashbookGetCashbookHistoryParams contains all the parameters to send to the API endpoint

	for the cashbook get cashbook history operation.

	Typically these are written to a http.Request.
*/
type CashbookGetCashbookHistoryParams struct {

	// CashbookID.
	//
	// Format: int32
	CashbookID int32

	// FullTextSearch.
	FullTextSearch *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cashbook get cashbook history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookGetCashbookHistoryParams) WithDefaults() *CashbookGetCashbookHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cashbook get cashbook history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookGetCashbookHistoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) WithTimeout(timeout time.Duration) *CashbookGetCashbookHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) WithContext(ctx context.Context) *CashbookGetCashbookHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) WithHTTPClient(client *http.Client) *CashbookGetCashbookHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCashbookID adds the cashbookID to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) WithCashbookID(cashbookID int32) *CashbookGetCashbookHistoryParams {
	o.SetCashbookID(cashbookID)
	return o
}

// SetCashbookID adds the cashbookId to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) SetCashbookID(cashbookID int32) {
	o.CashbookID = cashbookID
}

// WithFullTextSearch adds the fullTextSearch to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) WithFullTextSearch(fullTextSearch *string) *CashbookGetCashbookHistoryParams {
	o.SetFullTextSearch(fullTextSearch)
	return o
}

// SetFullTextSearch adds the fullTextSearch to the cashbook get cashbook history params
func (o *CashbookGetCashbookHistoryParams) SetFullTextSearch(fullTextSearch *string) {
	o.FullTextSearch = fullTextSearch
}

// WriteToRequest writes these params to a swagger request
func (o *CashbookGetCashbookHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cashbookID
	if err := r.SetPathParam("cashbookID", swag.FormatInt32(o.CashbookID)); err != nil {
		return err
	}

	if o.FullTextSearch != nil {

		// query param fullTextSearch
		var qrFullTextSearch string

		if o.FullTextSearch != nil {
			qrFullTextSearch = *o.FullTextSearch
		}
		qFullTextSearch := qrFullTextSearch
		if qFullTextSearch != "" {

			if err := r.SetQueryParam("fullTextSearch", qFullTextSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
