// Code generated by go-swagger; DO NOT EDIT.

package cashbook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// CashbookGetCashbookEntriesReader is a Reader for the CashbookGetCashbookEntries structure.
type CashbookGetCashbookEntriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CashbookGetCashbookEntriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCashbookGetCashbookEntriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/Cashbook/Entries] Cashbook_GetCashbookEntries", response, response.Code())
	}
}

// NewCashbookGetCashbookEntriesOK creates a CashbookGetCashbookEntriesOK with default headers values
func NewCashbookGetCashbookEntriesOK() *CashbookGetCashbookEntriesOK {
	return &CashbookGetCashbookEntriesOK{}
}

/*
CashbookGetCashbookEntriesOK describes a response with status code 200, with default header values.

Get an overview of all the entries in the cash book
*/
type CashbookGetCashbookEntriesOK struct {
	Payload *model.PageResultCashbookEntry
}

// IsSuccess returns true when this cashbook get cashbook entries o k response has a 2xx status code
func (o *CashbookGetCashbookEntriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cashbook get cashbook entries o k response has a 3xx status code
func (o *CashbookGetCashbookEntriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cashbook get cashbook entries o k response has a 4xx status code
func (o *CashbookGetCashbookEntriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cashbook get cashbook entries o k response has a 5xx status code
func (o *CashbookGetCashbookEntriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cashbook get cashbook entries o k response a status code equal to that given
func (o *CashbookGetCashbookEntriesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the cashbook get cashbook entries o k response
func (o *CashbookGetCashbookEntriesOK) Code() int {
	return 200
}

func (o *CashbookGetCashbookEntriesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/Cashbook/Entries][%d] cashbookGetCashbookEntriesOK %s", 200, payload)
}

func (o *CashbookGetCashbookEntriesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/Cashbook/Entries][%d] cashbookGetCashbookEntriesOK %s", 200, payload)
}

func (o *CashbookGetCashbookEntriesOK) GetPayload() *model.PageResultCashbookEntry {
	return o.Payload
}

func (o *CashbookGetCashbookEntriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.PageResultCashbookEntry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
