// Code generated by go-swagger; DO NOT EDIT.

package cashbook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCashbookGetCashbooksParams creates a new CashbookGetCashbooksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCashbookGetCashbooksParams() *CashbookGetCashbooksParams {
	return &CashbookGetCashbooksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCashbookGetCashbooksParamsWithTimeout creates a new CashbookGetCashbooksParams object
// with the ability to set a timeout on a request.
func NewCashbookGetCashbooksParamsWithTimeout(timeout time.Duration) *CashbookGetCashbooksParams {
	return &CashbookGetCashbooksParams{
		timeout: timeout,
	}
}

// NewCashbookGetCashbooksParamsWithContext creates a new CashbookGetCashbooksParams object
// with the ability to set a context for a request.
func NewCashbookGetCashbooksParamsWithContext(ctx context.Context) *CashbookGetCashbooksParams {
	return &CashbookGetCashbooksParams{
		Context: ctx,
	}
}

// NewCashbookGetCashbooksParamsWithHTTPClient creates a new CashbookGetCashbooksParams object
// with the ability to set a custom HTTPClient for a request.
func NewCashbookGetCashbooksParamsWithHTTPClient(client *http.Client) *CashbookGetCashbooksParams {
	return &CashbookGetCashbooksParams{
		HTTPClient: client,
	}
}

/*
CashbookGetCashbooksParams contains all the parameters to send to the API endpoint

	for the cashbook get cashbooks operation.

	Typically these are written to a http.Request.
*/
type CashbookGetCashbooksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cashbook get cashbooks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookGetCashbooksParams) WithDefaults() *CashbookGetCashbooksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cashbook get cashbooks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookGetCashbooksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cashbook get cashbooks params
func (o *CashbookGetCashbooksParams) WithTimeout(timeout time.Duration) *CashbookGetCashbooksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cashbook get cashbooks params
func (o *CashbookGetCashbooksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cashbook get cashbooks params
func (o *CashbookGetCashbooksParams) WithContext(ctx context.Context) *CashbookGetCashbooksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cashbook get cashbooks params
func (o *CashbookGetCashbooksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cashbook get cashbooks params
func (o *CashbookGetCashbooksParams) WithHTTPClient(client *http.Client) *CashbookGetCashbooksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cashbook get cashbooks params
func (o *CashbookGetCashbooksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CashbookGetCashbooksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
