// Code generated by go-swagger; DO NOT EDIT.

package cashbook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCashbookGetCashbookParams creates a new CashbookGetCashbookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCashbookGetCashbookParams() *CashbookGetCashbookParams {
	return &CashbookGetCashbookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCashbookGetCashbookParamsWithTimeout creates a new CashbookGetCashbookParams object
// with the ability to set a timeout on a request.
func NewCashbookGetCashbookParamsWithTimeout(timeout time.Duration) *CashbookGetCashbookParams {
	return &CashbookGetCashbookParams{
		timeout: timeout,
	}
}

// NewCashbookGetCashbookParamsWithContext creates a new CashbookGetCashbookParams object
// with the ability to set a context for a request.
func NewCashbookGetCashbookParamsWithContext(ctx context.Context) *CashbookGetCashbookParams {
	return &CashbookGetCashbookParams{
		Context: ctx,
	}
}

// NewCashbookGetCashbookParamsWithHTTPClient creates a new CashbookGetCashbookParams object
// with the ability to set a custom HTTPClient for a request.
func NewCashbookGetCashbookParamsWithHTTPClient(client *http.Client) *CashbookGetCashbookParams {
	return &CashbookGetCashbookParams{
		HTTPClient: client,
	}
}

/*
CashbookGetCashbookParams contains all the parameters to send to the API endpoint

	for the cashbook get cashbook operation.

	Typically these are written to a http.Request.
*/
type CashbookGetCashbookParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cashbook get cashbook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookGetCashbookParams) WithDefaults() *CashbookGetCashbookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cashbook get cashbook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookGetCashbookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cashbook get cashbook params
func (o *CashbookGetCashbookParams) WithTimeout(timeout time.Duration) *CashbookGetCashbookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cashbook get cashbook params
func (o *CashbookGetCashbookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cashbook get cashbook params
func (o *CashbookGetCashbookParams) WithContext(ctx context.Context) *CashbookGetCashbookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cashbook get cashbook params
func (o *CashbookGetCashbookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cashbook get cashbook params
func (o *CashbookGetCashbookParams) WithHTTPClient(client *http.Client) *CashbookGetCashbookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cashbook get cashbook params
func (o *CashbookGetCashbookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CashbookGetCashbookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
