// Code generated by go-swagger; DO NOT EDIT.

package cashbook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCashbookCloseCashbookParams creates a new CashbookCloseCashbookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCashbookCloseCashbookParams() *CashbookCloseCashbookParams {
	return &CashbookCloseCashbookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCashbookCloseCashbookParamsWithTimeout creates a new CashbookCloseCashbookParams object
// with the ability to set a timeout on a request.
func NewCashbookCloseCashbookParamsWithTimeout(timeout time.Duration) *CashbookCloseCashbookParams {
	return &CashbookCloseCashbookParams{
		timeout: timeout,
	}
}

// NewCashbookCloseCashbookParamsWithContext creates a new CashbookCloseCashbookParams object
// with the ability to set a context for a request.
func NewCashbookCloseCashbookParamsWithContext(ctx context.Context) *CashbookCloseCashbookParams {
	return &CashbookCloseCashbookParams{
		Context: ctx,
	}
}

// NewCashbookCloseCashbookParamsWithHTTPClient creates a new CashbookCloseCashbookParams object
// with the ability to set a custom HTTPClient for a request.
func NewCashbookCloseCashbookParamsWithHTTPClient(client *http.Client) *CashbookCloseCashbookParams {
	return &CashbookCloseCashbookParams{
		HTTPClient: client,
	}
}

/*
CashbookCloseCashbookParams contains all the parameters to send to the API endpoint

	for the cashbook close cashbook operation.

	Typically these are written to a http.Request.
*/
type CashbookCloseCashbookParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cashbook close cashbook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookCloseCashbookParams) WithDefaults() *CashbookCloseCashbookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cashbook close cashbook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookCloseCashbookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cashbook close cashbook params
func (o *CashbookCloseCashbookParams) WithTimeout(timeout time.Duration) *CashbookCloseCashbookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cashbook close cashbook params
func (o *CashbookCloseCashbookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cashbook close cashbook params
func (o *CashbookCloseCashbookParams) WithContext(ctx context.Context) *CashbookCloseCashbookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cashbook close cashbook params
func (o *CashbookCloseCashbookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cashbook close cashbook params
func (o *CashbookCloseCashbookParams) WithHTTPClient(client *http.Client) *CashbookCloseCashbookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cashbook close cashbook params
func (o *CashbookCloseCashbookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CashbookCloseCashbookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
