// Code generated by go-swagger; DO NOT EDIT.

package cashbook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewCashbookPostCashbookEntryParams creates a new CashbookPostCashbookEntryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCashbookPostCashbookEntryParams() *CashbookPostCashbookEntryParams {
	return &CashbookPostCashbookEntryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCashbookPostCashbookEntryParamsWithTimeout creates a new CashbookPostCashbookEntryParams object
// with the ability to set a timeout on a request.
func NewCashbookPostCashbookEntryParamsWithTimeout(timeout time.Duration) *CashbookPostCashbookEntryParams {
	return &CashbookPostCashbookEntryParams{
		timeout: timeout,
	}
}

// NewCashbookPostCashbookEntryParamsWithContext creates a new CashbookPostCashbookEntryParams object
// with the ability to set a context for a request.
func NewCashbookPostCashbookEntryParamsWithContext(ctx context.Context) *CashbookPostCashbookEntryParams {
	return &CashbookPostCashbookEntryParams{
		Context: ctx,
	}
}

// NewCashbookPostCashbookEntryParamsWithHTTPClient creates a new CashbookPostCashbookEntryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCashbookPostCashbookEntryParamsWithHTTPClient(client *http.Client) *CashbookPostCashbookEntryParams {
	return &CashbookPostCashbookEntryParams{
		HTTPClient: client,
	}
}

/*
CashbookPostCashbookEntryParams contains all the parameters to send to the API endpoint

	for the cashbook post cashbook entry operation.

	Typically these are written to a http.Request.
*/
type CashbookPostCashbookEntryParams struct {

	// CashbookInputEntry.
	CashbookInputEntry *model.CashbookEntry

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cashbook post cashbook entry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookPostCashbookEntryParams) WithDefaults() *CashbookPostCashbookEntryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cashbook post cashbook entry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CashbookPostCashbookEntryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) WithTimeout(timeout time.Duration) *CashbookPostCashbookEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) WithContext(ctx context.Context) *CashbookPostCashbookEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) WithHTTPClient(client *http.Client) *CashbookPostCashbookEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCashbookInputEntry adds the cashbookInputEntry to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) WithCashbookInputEntry(cashbookInputEntry *model.CashbookEntry) *CashbookPostCashbookEntryParams {
	o.SetCashbookInputEntry(cashbookInputEntry)
	return o
}

// SetCashbookInputEntry adds the cashbookInputEntry to the cashbook post cashbook entry params
func (o *CashbookPostCashbookEntryParams) SetCashbookInputEntry(cashbookInputEntry *model.CashbookEntry) {
	o.CashbookInputEntry = cashbookInputEntry
}

// WriteToRequest writes these params to a swagger request
func (o *CashbookPostCashbookEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CashbookInputEntry != nil {
		if err := r.SetBodyParam(o.CashbookInputEntry); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
