// Code generated by go-swagger; DO NOT EDIT.

package party

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PartyPatchPartiesReader is a Reader for the PartyPatchParties structure.
type PartyPatchPartiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PartyPatchPartiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPartyPatchPartiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/parties/{partyID}] Party_PatchParties", response, response.Code())
	}
}

// NewPartyPatchPartiesOK creates a PartyPatchPartiesOK with default headers values
func NewPartyPatchPartiesOK() *PartyPatchPartiesOK {
	return &PartyPatchPartiesOK{}
}

/*
PartyPatchPartiesOK describes a response with status code 200, with default header values.

Patch a party
*/
type PartyPatchPartiesOK struct {
}

// IsSuccess returns true when this party patch parties o k response has a 2xx status code
func (o *PartyPatchPartiesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this party patch parties o k response has a 3xx status code
func (o *PartyPatchPartiesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this party patch parties o k response has a 4xx status code
func (o *PartyPatchPartiesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this party patch parties o k response has a 5xx status code
func (o *PartyPatchPartiesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this party patch parties o k response a status code equal to that given
func (o *PartyPatchPartiesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the party patch parties o k response
func (o *PartyPatchPartiesOK) Code() int {
	return 200
}

func (o *PartyPatchPartiesOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/parties/{partyID}][%d] partyPatchPartiesOK", 200)
}

func (o *PartyPatchPartiesOK) String() string {
	return fmt.Sprintf("[PATCH /v1/parties/{partyID}][%d] partyPatchPartiesOK", 200)
}

func (o *PartyPatchPartiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
