// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// AccountGetAccountInformationReader is a Reader for the AccountGetAccountInformation structure.
type AccountGetAccountInformationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountGetAccountInformationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountGetAccountInformationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/account/accountInformation] Account_GetAccountInformation", response, response.Code())
	}
}

// NewAccountGetAccountInformationOK creates a AccountGetAccountInformationOK with default headers values
func NewAccountGetAccountInformationOK() *AccountGetAccountInformationOK {
	return &AccountGetAccountInformationOK{}
}

/*
AccountGetAccountInformationOK describes a response with status code 200, with default header values.

Get account information
*/
type AccountGetAccountInformationOK struct {
	Payload *model.AccountInformation
}

// IsSuccess returns true when this account get account information o k response has a 2xx status code
func (o *AccountGetAccountInformationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this account get account information o k response has a 3xx status code
func (o *AccountGetAccountInformationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account get account information o k response has a 4xx status code
func (o *AccountGetAccountInformationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this account get account information o k response has a 5xx status code
func (o *AccountGetAccountInformationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this account get account information o k response a status code equal to that given
func (o *AccountGetAccountInformationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the account get account information o k response
func (o *AccountGetAccountInformationOK) Code() int {
	return 200
}

func (o *AccountGetAccountInformationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/account/accountInformation][%d] accountGetAccountInformationOK %s", 200, payload)
}

func (o *AccountGetAccountInformationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/account/accountInformation][%d] accountGetAccountInformationOK %s", 200, payload)
}

func (o *AccountGetAccountInformationOK) GetPayload() *model.AccountInformation {
	return o.Payload
}

func (o *AccountGetAccountInformationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.AccountInformation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
