// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// AccountUpdateLicenseReader is a Reader for the AccountUpdateLicense structure.
type AccountUpdateLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountUpdateLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountUpdateLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/account/license] Account_UpdateLicense", response, response.Code())
	}
}

// NewAccountUpdateLicenseOK creates a AccountUpdateLicenseOK with default headers values
func NewAccountUpdateLicenseOK() *AccountUpdateLicenseOK {
	return &AccountUpdateLicenseOK{}
}

/*
AccountUpdateLicenseOK describes a response with status code 200, with default header values.

Update a company license
*/
type AccountUpdateLicenseOK struct {
	Payload *model.UpdateLicenseResponseModel
}

// IsSuccess returns true when this account update license o k response has a 2xx status code
func (o *AccountUpdateLicenseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this account update license o k response has a 3xx status code
func (o *AccountUpdateLicenseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account update license o k response has a 4xx status code
func (o *AccountUpdateLicenseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this account update license o k response has a 5xx status code
func (o *AccountUpdateLicenseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this account update license o k response a status code equal to that given
func (o *AccountUpdateLicenseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the account update license o k response
func (o *AccountUpdateLicenseOK) Code() int {
	return 200
}

func (o *AccountUpdateLicenseOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/account/license][%d] accountUpdateLicenseOK %s", 200, payload)
}

func (o *AccountUpdateLicenseOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/account/license][%d] accountUpdateLicenseOK %s", 200, payload)
}

func (o *AccountUpdateLicenseOK) GetPayload() *model.UpdateLicenseResponseModel {
	return o.Payload
}

func (o *AccountUpdateLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.UpdateLicenseResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
