// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AccountPostSequencesReader is a Reader for the AccountPostSequences structure.
type AccountPostSequencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountPostSequencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountPostSequencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/account/sequences] Account_PostSequences", response, response.Code())
	}
}

// NewAccountPostSequencesOK creates a AccountPostSequencesOK with default headers values
func NewAccountPostSequencesOK() *AccountPostSequencesOK {
	return &AccountPostSequencesOK{}
}

/*
AccountPostSequencesOK describes a response with status code 200, with default header values.

OK
*/
type AccountPostSequencesOK struct {
	Payload interface{}
}

// IsSuccess returns true when this account post sequences o k response has a 2xx status code
func (o *AccountPostSequencesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this account post sequences o k response has a 3xx status code
func (o *AccountPostSequencesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account post sequences o k response has a 4xx status code
func (o *AccountPostSequencesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this account post sequences o k response has a 5xx status code
func (o *AccountPostSequencesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this account post sequences o k response a status code equal to that given
func (o *AccountPostSequencesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the account post sequences o k response
func (o *AccountPostSequencesOK) Code() int {
	return 200
}

func (o *AccountPostSequencesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/account/sequences][%d] accountPostSequencesOK %s", 200, payload)
}

func (o *AccountPostSequencesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/account/sequences][%d] accountPostSequencesOK %s", 200, payload)
}

func (o *AccountPostSequencesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *AccountPostSequencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
