// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewAccountAddLicenseBillableParams creates a new AccountAddLicenseBillableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAccountAddLicenseBillableParams() *AccountAddLicenseBillableParams {
	return &AccountAddLicenseBillableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAccountAddLicenseBillableParamsWithTimeout creates a new AccountAddLicenseBillableParams object
// with the ability to set a timeout on a request.
func NewAccountAddLicenseBillableParamsWithTimeout(timeout time.Duration) *AccountAddLicenseBillableParams {
	return &AccountAddLicenseBillableParams{
		timeout: timeout,
	}
}

// NewAccountAddLicenseBillableParamsWithContext creates a new AccountAddLicenseBillableParams object
// with the ability to set a context for a request.
func NewAccountAddLicenseBillableParamsWithContext(ctx context.Context) *AccountAddLicenseBillableParams {
	return &AccountAddLicenseBillableParams{
		Context: ctx,
	}
}

// NewAccountAddLicenseBillableParamsWithHTTPClient creates a new AccountAddLicenseBillableParams object
// with the ability to set a custom HTTPClient for a request.
func NewAccountAddLicenseBillableParamsWithHTTPClient(client *http.Client) *AccountAddLicenseBillableParams {
	return &AccountAddLicenseBillableParams{
		HTTPClient: client,
	}
}

/*
AccountAddLicenseBillableParams contains all the parameters to send to the API endpoint

	for the account add license billable operation.

	Typically these are written to a http.Request.
*/
type AccountAddLicenseBillableParams struct {

	// LicenseBillableModel.
	LicenseBillableModel *model.AddNewLicenseBillableModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the account add license billable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AccountAddLicenseBillableParams) WithDefaults() *AccountAddLicenseBillableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the account add license billable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AccountAddLicenseBillableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the account add license billable params
func (o *AccountAddLicenseBillableParams) WithTimeout(timeout time.Duration) *AccountAddLicenseBillableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the account add license billable params
func (o *AccountAddLicenseBillableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the account add license billable params
func (o *AccountAddLicenseBillableParams) WithContext(ctx context.Context) *AccountAddLicenseBillableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the account add license billable params
func (o *AccountAddLicenseBillableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the account add license billable params
func (o *AccountAddLicenseBillableParams) WithHTTPClient(client *http.Client) *AccountAddLicenseBillableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the account add license billable params
func (o *AccountAddLicenseBillableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLicenseBillableModel adds the licenseBillableModel to the account add license billable params
func (o *AccountAddLicenseBillableParams) WithLicenseBillableModel(licenseBillableModel *model.AddNewLicenseBillableModel) *AccountAddLicenseBillableParams {
	o.SetLicenseBillableModel(licenseBillableModel)
	return o
}

// SetLicenseBillableModel adds the licenseBillableModel to the account add license billable params
func (o *AccountAddLicenseBillableParams) SetLicenseBillableModel(licenseBillableModel *model.AddNewLicenseBillableModel) {
	o.LicenseBillableModel = licenseBillableModel
}

// WriteToRequest writes these params to a swagger request
func (o *AccountAddLicenseBillableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.LicenseBillableModel != nil {
		if err := r.SetBodyParam(o.LicenseBillableModel); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
