// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProductGetProductsParams creates a new ProductGetProductsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProductGetProductsParams() *ProductGetProductsParams {
	return &ProductGetProductsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProductGetProductsParamsWithTimeout creates a new ProductGetProductsParams object
// with the ability to set a timeout on a request.
func NewProductGetProductsParamsWithTimeout(timeout time.Duration) *ProductGetProductsParams {
	return &ProductGetProductsParams{
		timeout: timeout,
	}
}

// NewProductGetProductsParamsWithContext creates a new ProductGetProductsParams object
// with the ability to set a context for a request.
func NewProductGetProductsParamsWithContext(ctx context.Context) *ProductGetProductsParams {
	return &ProductGetProductsParams{
		Context: ctx,
	}
}

// NewProductGetProductsParamsWithHTTPClient creates a new ProductGetProductsParams object
// with the ability to set a custom HTTPClient for a request.
func NewProductGetProductsParamsWithHTTPClient(client *http.Client) *ProductGetProductsParams {
	return &ProductGetProductsParams{
		HTTPClient: client,
	}
}

/*
ProductGetProductsParams contains all the parameters to send to the API endpoint

	for the product get products operation.

	Typically these are written to a http.Request.
*/
type ProductGetProductsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the product get products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductGetProductsParams) WithDefaults() *ProductGetProductsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the product get products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductGetProductsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the product get products params
func (o *ProductGetProductsParams) WithTimeout(timeout time.Duration) *ProductGetProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the product get products params
func (o *ProductGetProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the product get products params
func (o *ProductGetProductsParams) WithContext(ctx context.Context) *ProductGetProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the product get products params
func (o *ProductGetProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the product get products params
func (o *ProductGetProductsParams) WithHTTPClient(client *http.Client) *ProductGetProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the product get products params
func (o *ProductGetProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ProductGetProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
