// Code generated by go-swagger; DO NOT EDIT.

package g_l_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GLAccountPostGLAccountReader is a Reader for the GLAccountPostGLAccount structure.
type GLAccountPostGLAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GLAccountPostGLAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGLAccountPostGLAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/glaccounts] GLAccount_PostGLAccount", response, response.Code())
	}
}

// NewGLAccountPostGLAccountOK creates a GLAccountPostGLAccountOK with default headers values
func NewGLAccountPostGLAccountOK() *GLAccountPostGLAccountOK {
	return &GLAccountPostGLAccountOK{}
}

/*
GLAccountPostGLAccountOK describes a response with status code 200, with default header values.

Save an general ledger account code
*/
type GLAccountPostGLAccountOK struct {
	Payload int32
}

// IsSuccess returns true when this g l account post g l account o k response has a 2xx status code
func (o *GLAccountPostGLAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this g l account post g l account o k response has a 3xx status code
func (o *GLAccountPostGLAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this g l account post g l account o k response has a 4xx status code
func (o *GLAccountPostGLAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this g l account post g l account o k response has a 5xx status code
func (o *GLAccountPostGLAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this g l account post g l account o k response a status code equal to that given
func (o *GLAccountPostGLAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the g l account post g l account o k response
func (o *GLAccountPostGLAccountOK) Code() int {
	return 200
}

func (o *GLAccountPostGLAccountOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/glaccounts][%d] gLAccountPostGLAccountOK %s", 200, payload)
}

func (o *GLAccountPostGLAccountOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/glaccounts][%d] gLAccountPostGLAccountOK %s", 200, payload)
}

func (o *GLAccountPostGLAccountOK) GetPayload() int32 {
	return o.Payload
}

func (o *GLAccountPostGLAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
