// Code generated by go-swagger; DO NOT EDIT.

package g_l_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GLAccountPostGLAccountBulkReader is a Reader for the GLAccountPostGLAccountBulk structure.
type GLAccountPostGLAccountBulkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GLAccountPostGLAccountBulkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGLAccountPostGLAccountBulkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/glaccounts/commands/import] GLAccount_PostGLAccountBulk", response, response.Code())
	}
}

// NewGLAccountPostGLAccountBulkOK creates a GLAccountPostGLAccountBulkOK with default headers values
func NewGLAccountPostGLAccountBulkOK() *GLAccountPostGLAccountBulkOK {
	return &GLAccountPostGLAccountBulkOK{}
}

/*
GLAccountPostGLAccountBulkOK describes a response with status code 200, with default header values.

Save an general ledger account code
*/
type GLAccountPostGLAccountBulkOK struct {
	Payload int32
}

// IsSuccess returns true when this g l account post g l account bulk o k response has a 2xx status code
func (o *GLAccountPostGLAccountBulkOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this g l account post g l account bulk o k response has a 3xx status code
func (o *GLAccountPostGLAccountBulkOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this g l account post g l account bulk o k response has a 4xx status code
func (o *GLAccountPostGLAccountBulkOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this g l account post g l account bulk o k response has a 5xx status code
func (o *GLAccountPostGLAccountBulkOK) IsServerError() bool {
	return false
}

// IsCode returns true when this g l account post g l account bulk o k response a status code equal to that given
func (o *GLAccountPostGLAccountBulkOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the g l account post g l account bulk o k response
func (o *GLAccountPostGLAccountBulkOK) Code() int {
	return 200
}

func (o *GLAccountPostGLAccountBulkOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/glaccounts/commands/import][%d] gLAccountPostGLAccountBulkOK %s", 200, payload)
}

func (o *GLAccountPostGLAccountBulkOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/glaccounts/commands/import][%d] gLAccountPostGLAccountBulkOK %s", 200, payload)
}

func (o *GLAccountPostGLAccountBulkOK) GetPayload() int32 {
	return o.Payload
}

func (o *GLAccountPostGLAccountBulkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
