// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFileGetOrdersParams creates a new FileGetOrdersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFileGetOrdersParams() *FileGetOrdersParams {
	return &FileGetOrdersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFileGetOrdersParamsWithTimeout creates a new FileGetOrdersParams object
// with the ability to set a timeout on a request.
func NewFileGetOrdersParamsWithTimeout(timeout time.Duration) *FileGetOrdersParams {
	return &FileGetOrdersParams{
		timeout: timeout,
	}
}

// NewFileGetOrdersParamsWithContext creates a new FileGetOrdersParams object
// with the ability to set a context for a request.
func NewFileGetOrdersParamsWithContext(ctx context.Context) *FileGetOrdersParams {
	return &FileGetOrdersParams{
		Context: ctx,
	}
}

// NewFileGetOrdersParamsWithHTTPClient creates a new FileGetOrdersParams object
// with the ability to set a custom HTTPClient for a request.
func NewFileGetOrdersParamsWithHTTPClient(client *http.Client) *FileGetOrdersParams {
	return &FileGetOrdersParams{
		HTTPClient: client,
	}
}

/*
FileGetOrdersParams contains all the parameters to send to the API endpoint

	for the file get orders operation.

	Typically these are written to a http.Request.
*/
type FileGetOrdersParams struct {

	// FileID.
	//
	// Format: uuid
	FileID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the file get orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FileGetOrdersParams) WithDefaults() *FileGetOrdersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the file get orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FileGetOrdersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the file get orders params
func (o *FileGetOrdersParams) WithTimeout(timeout time.Duration) *FileGetOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the file get orders params
func (o *FileGetOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the file get orders params
func (o *FileGetOrdersParams) WithContext(ctx context.Context) *FileGetOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the file get orders params
func (o *FileGetOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the file get orders params
func (o *FileGetOrdersParams) WithHTTPClient(client *http.Client) *FileGetOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the file get orders params
func (o *FileGetOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileID adds the fileID to the file get orders params
func (o *FileGetOrdersParams) WithFileID(fileID strfmt.UUID) *FileGetOrdersParams {
	o.SetFileID(fileID)
	return o
}

// SetFileID adds the fileId to the file get orders params
func (o *FileGetOrdersParams) SetFileID(fileID strfmt.UUID) {
	o.FileID = fileID
}

// WriteToRequest writes these params to a swagger request
func (o *FileGetOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fileID
	if err := r.SetPathParam("fileID", o.FileID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
