// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WebhookDeleteWebhooksReader is a Reader for the WebhookDeleteWebhooks structure.
type WebhookDeleteWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WebhookDeleteWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWebhookDeleteWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/webhooks/{webhookID}] Webhook_DeleteWebhooks", response, response.Code())
	}
}

// NewWebhookDeleteWebhooksOK creates a WebhookDeleteWebhooksOK with default headers values
func NewWebhookDeleteWebhooksOK() *WebhookDeleteWebhooksOK {
	return &WebhookDeleteWebhooksOK{}
}

/*
WebhookDeleteWebhooksOK describes a response with status code 200, with default header values.

Delete an webhook
*/
type WebhookDeleteWebhooksOK struct {
	Payload string
}

// IsSuccess returns true when this webhook delete webhooks o k response has a 2xx status code
func (o *WebhookDeleteWebhooksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this webhook delete webhooks o k response has a 3xx status code
func (o *WebhookDeleteWebhooksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this webhook delete webhooks o k response has a 4xx status code
func (o *WebhookDeleteWebhooksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this webhook delete webhooks o k response has a 5xx status code
func (o *WebhookDeleteWebhooksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this webhook delete webhooks o k response a status code equal to that given
func (o *WebhookDeleteWebhooksOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the webhook delete webhooks o k response
func (o *WebhookDeleteWebhooksOK) Code() int {
	return 200
}

func (o *WebhookDeleteWebhooksOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/webhooks/{webhookID}][%d] webhookDeleteWebhooksOK %s", 200, payload)
}

func (o *WebhookDeleteWebhooksOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/webhooks/{webhookID}][%d] webhookDeleteWebhooksOK %s", 200, payload)
}

func (o *WebhookDeleteWebhooksOK) GetPayload() string {
	return o.Payload
}

func (o *WebhookDeleteWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
