// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// WebhookGetWebhooksReader is a Reader for the WebhookGetWebhooks structure.
type WebhookGetWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WebhookGetWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWebhookGetWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/webhooks] Webhook_GetWebhooks", response, response.Code())
	}
}

// NewWebhookGetWebhooksOK creates a WebhookGetWebhooksOK with default headers values
func NewWebhookGetWebhooksOK() *WebhookGetWebhooksOK {
	return &WebhookGetWebhooksOK{}
}

/*
WebhookGetWebhooksOK describes a response with status code 200, with default header values.

Get webhooks
*/
type WebhookGetWebhooksOK struct {
	Payload *model.Webhook
}

// IsSuccess returns true when this webhook get webhooks o k response has a 2xx status code
func (o *WebhookGetWebhooksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this webhook get webhooks o k response has a 3xx status code
func (o *WebhookGetWebhooksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this webhook get webhooks o k response has a 4xx status code
func (o *WebhookGetWebhooksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this webhook get webhooks o k response has a 5xx status code
func (o *WebhookGetWebhooksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this webhook get webhooks o k response a status code equal to that given
func (o *WebhookGetWebhooksOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the webhook get webhooks o k response
func (o *WebhookGetWebhooksOK) Code() int {
	return 200
}

func (o *WebhookGetWebhooksOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/webhooks][%d] webhookGetWebhooksOK %s", 200, payload)
}

func (o *WebhookGetWebhooksOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/webhooks][%d] webhookGetWebhooksOK %s", 200, payload)
}

func (o *WebhookGetWebhooksOK) GetPayload() *model.Webhook {
	return o.Payload
}

func (o *WebhookGetWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Webhook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
