// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewWebhookPostWebhookParams creates a new WebhookPostWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWebhookPostWebhookParams() *WebhookPostWebhookParams {
	return &WebhookPostWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWebhookPostWebhookParamsWithTimeout creates a new WebhookPostWebhookParams object
// with the ability to set a timeout on a request.
func NewWebhookPostWebhookParamsWithTimeout(timeout time.Duration) *WebhookPostWebhookParams {
	return &WebhookPostWebhookParams{
		timeout: timeout,
	}
}

// NewWebhookPostWebhookParamsWithContext creates a new WebhookPostWebhookParams object
// with the ability to set a context for a request.
func NewWebhookPostWebhookParamsWithContext(ctx context.Context) *WebhookPostWebhookParams {
	return &WebhookPostWebhookParams{
		Context: ctx,
	}
}

// NewWebhookPostWebhookParamsWithHTTPClient creates a new WebhookPostWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewWebhookPostWebhookParamsWithHTTPClient(client *http.Client) *WebhookPostWebhookParams {
	return &WebhookPostWebhookParams{
		HTTPClient: client,
	}
}

/*
WebhookPostWebhookParams contains all the parameters to send to the API endpoint

	for the webhook post webhook operation.

	Typically these are written to a http.Request.
*/
type WebhookPostWebhookParams struct {

	// Webhook.
	Webhook *model.Webhook

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the webhook post webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebhookPostWebhookParams) WithDefaults() *WebhookPostWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the webhook post webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebhookPostWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the webhook post webhook params
func (o *WebhookPostWebhookParams) WithTimeout(timeout time.Duration) *WebhookPostWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the webhook post webhook params
func (o *WebhookPostWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the webhook post webhook params
func (o *WebhookPostWebhookParams) WithContext(ctx context.Context) *WebhookPostWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the webhook post webhook params
func (o *WebhookPostWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the webhook post webhook params
func (o *WebhookPostWebhookParams) WithHTTPClient(client *http.Client) *WebhookPostWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the webhook post webhook params
func (o *WebhookPostWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWebhook adds the webhook to the webhook post webhook params
func (o *WebhookPostWebhookParams) WithWebhook(webhook *model.Webhook) *WebhookPostWebhookParams {
	o.SetWebhook(webhook)
	return o
}

// SetWebhook adds the webhook to the webhook post webhook params
func (o *WebhookPostWebhookParams) SetWebhook(webhook *model.Webhook) {
	o.Webhook = webhook
}

// WriteToRequest writes these params to a swagger request
func (o *WebhookPostWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Webhook != nil {
		if err := r.SetBodyParam(o.Webhook); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
