// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewWebhookDeleteWebhooksParams creates a new WebhookDeleteWebhooksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWebhookDeleteWebhooksParams() *WebhookDeleteWebhooksParams {
	return &WebhookDeleteWebhooksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWebhookDeleteWebhooksParamsWithTimeout creates a new WebhookDeleteWebhooksParams object
// with the ability to set a timeout on a request.
func NewWebhookDeleteWebhooksParamsWithTimeout(timeout time.Duration) *WebhookDeleteWebhooksParams {
	return &WebhookDeleteWebhooksParams{
		timeout: timeout,
	}
}

// NewWebhookDeleteWebhooksParamsWithContext creates a new WebhookDeleteWebhooksParams object
// with the ability to set a context for a request.
func NewWebhookDeleteWebhooksParamsWithContext(ctx context.Context) *WebhookDeleteWebhooksParams {
	return &WebhookDeleteWebhooksParams{
		Context: ctx,
	}
}

// NewWebhookDeleteWebhooksParamsWithHTTPClient creates a new WebhookDeleteWebhooksParams object
// with the ability to set a custom HTTPClient for a request.
func NewWebhookDeleteWebhooksParamsWithHTTPClient(client *http.Client) *WebhookDeleteWebhooksParams {
	return &WebhookDeleteWebhooksParams{
		HTTPClient: client,
	}
}

/*
WebhookDeleteWebhooksParams contains all the parameters to send to the API endpoint

	for the webhook delete webhooks operation.

	Typically these are written to a http.Request.
*/
type WebhookDeleteWebhooksParams struct {

	// WebhookID.
	//
	// Format: int32
	WebhookID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the webhook delete webhooks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebhookDeleteWebhooksParams) WithDefaults() *WebhookDeleteWebhooksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the webhook delete webhooks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebhookDeleteWebhooksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) WithTimeout(timeout time.Duration) *WebhookDeleteWebhooksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) WithContext(ctx context.Context) *WebhookDeleteWebhooksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) WithHTTPClient(client *http.Client) *WebhookDeleteWebhooksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWebhookID adds the webhookID to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) WithWebhookID(webhookID int32) *WebhookDeleteWebhooksParams {
	o.SetWebhookID(webhookID)
	return o
}

// SetWebhookID adds the webhookId to the webhook delete webhooks params
func (o *WebhookDeleteWebhooksParams) SetWebhookID(webhookID int32) {
	o.WebhookID = webhookID
}

// WriteToRequest writes these params to a swagger request
func (o *WebhookDeleteWebhooksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param webhookID
	if err := r.SetPathParam("webhookID", swag.FormatInt32(o.WebhookID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
