// Code generated by go-swagger; DO NOT EDIT.

package o_auth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/becoded/billit/model"
)

// NewOAuth2PostTokenParams creates a new OAuth2PostTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOAuth2PostTokenParams() *OAuth2PostTokenParams {
	return &OAuth2PostTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOAuth2PostTokenParamsWithTimeout creates a new OAuth2PostTokenParams object
// with the ability to set a timeout on a request.
func NewOAuth2PostTokenParamsWithTimeout(timeout time.Duration) *OAuth2PostTokenParams {
	return &OAuth2PostTokenParams{
		timeout: timeout,
	}
}

// NewOAuth2PostTokenParamsWithContext creates a new OAuth2PostTokenParams object
// with the ability to set a context for a request.
func NewOAuth2PostTokenParamsWithContext(ctx context.Context) *OAuth2PostTokenParams {
	return &OAuth2PostTokenParams{
		Context: ctx,
	}
}

// NewOAuth2PostTokenParamsWithHTTPClient creates a new OAuth2PostTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewOAuth2PostTokenParamsWithHTTPClient(client *http.Client) *OAuth2PostTokenParams {
	return &OAuth2PostTokenParams{
		HTTPClient: client,
	}
}

/*
OAuth2PostTokenParams contains all the parameters to send to the API endpoint

	for the o auth2 post token operation.

	Typically these are written to a http.Request.
*/
type OAuth2PostTokenParams struct {

	// OAuthAccessTokenRequest.
	OAuthAccessTokenRequest *model.OAuthAccessTokenRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the o auth2 post token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OAuth2PostTokenParams) WithDefaults() *OAuth2PostTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the o auth2 post token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OAuth2PostTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the o auth2 post token params
func (o *OAuth2PostTokenParams) WithTimeout(timeout time.Duration) *OAuth2PostTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the o auth2 post token params
func (o *OAuth2PostTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the o auth2 post token params
func (o *OAuth2PostTokenParams) WithContext(ctx context.Context) *OAuth2PostTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the o auth2 post token params
func (o *OAuth2PostTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the o auth2 post token params
func (o *OAuth2PostTokenParams) WithHTTPClient(client *http.Client) *OAuth2PostTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the o auth2 post token params
func (o *OAuth2PostTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOAuthAccessTokenRequest adds the oAuthAccessTokenRequest to the o auth2 post token params
func (o *OAuth2PostTokenParams) WithOAuthAccessTokenRequest(oAuthAccessTokenRequest *model.OAuthAccessTokenRequest) *OAuth2PostTokenParams {
	o.SetOAuthAccessTokenRequest(oAuthAccessTokenRequest)
	return o
}

// SetOAuthAccessTokenRequest adds the oAuthAccessTokenRequest to the o auth2 post token params
func (o *OAuth2PostTokenParams) SetOAuthAccessTokenRequest(oAuthAccessTokenRequest *model.OAuthAccessTokenRequest) {
	o.OAuthAccessTokenRequest = oAuthAccessTokenRequest
}

// WriteToRequest writes these params to a swagger request
func (o *OAuth2PostTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OAuthAccessTokenRequest != nil {
		if err := r.SetBodyParam(o.OAuthAccessTokenRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
